In [3]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

import os

In [4]:
import pandas as pd

# Load everything (fast)
df_color = pd.read_parquet("/home/sagemaker-user/user-default-efs/vjepa2/classifier/output/color_inference_18m/predictions.parquet")
df_view = pd.read_parquet("/home/sagemaker-user/user-default-efs/vjepa2/classifier/output/view_inference_18m/predictions.parquet")

In [67]:
print(len(df_color))
df_color.head()

18203528

,s3_uri,is_color,confidence,status
0,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703111357.10353285/1.2.276.0.7230010.3.1.3.1714512485.1.1703111357.10353286/1.2.276.0.7230010.3.1.4.1714512485.1.1703111357.10353287.mp4,Yes,0.915527,OK
1,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703111357.10353285/1.2.276.0.7230010.3.1.3.1714512485.1.1703111357.10353286/1.2.276.0.7230010.3.1.4.1714512485.1.1703111381.10353325.mp4,No,0.935547,OK
2,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703111357.10353285/1.2.276.0.7230010.3.1.3.1714512485.1.1703111357.10353286/1.2.276.0.7230010.3.1.4.1714512485.1.1703111395.10353351.mp4,Yes,0.906738,OK
3,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703111357.10353285/1.2.276.0.7230010.3.1.3.1714512485.1.1703111357.10353286/1.2.276.0.7230010.3.1.4.1714578744.1.1703111357.7964267.mp4,No,0.963379,OK
4,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703111357.10353285/1.2.276.0.7230010.3.1.3.1714512485.1.1703111357.10353286/1.2.276.0.7230010.3.1.4.1714578744.1.1703111378.7964301.mp4,No,0.956055,OK

In [69]:
df_color["is_color"].value_counts()

is_color
No     11037415
Yes     7165998
            115
Name: count, dtype: int64

In [68]:
print(len(df_view))
df_view.head()

18236344

,s3_uri,prediction,confidence,status
0,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703111357.10353285/1.2.276.0.7230010.3.1.3.1714512485.1.1703111357.10353286/1.2.276.0.7230010.3.1.4.1714512485.1.1703111357.10353287.mp4,A4C,0.573242,OK
1,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703111357.10353285/1.2.276.0.7230010.3.1.3.1714512485.1.1703111357.10353286/1.2.276.0.7230010.3.1.4.1714512485.1.1703111381.10353325.mp4,Exclude,0.835449,OK
2,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703111357.10353285/1.2.276.0.7230010.3.1.3.1714512485.1.1703111357.10353286/1.2.276.0.7230010.3.1.4.1714512485.1.1703111395.10353351.mp4,Exclude,0.561035,OK
3,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703111357.10353285/1.2.276.0.7230010.3.1.3.1714512485.1.1703111357.10353286/1.2.276.0.7230010.3.1.4.1714578744.1.1703111357.7964267.mp4,Exclude,0.439697,OK
4,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703111357.10353285/1.2.276.0.7230010.3.1.3.1714512485.1.1703111357.10353286/1.2.276.0.7230010.3.1.4.1714578744.1.1703111378.7964301.mp4,PSAX-PM,0.822266,OK

In [71]:
df_view["prediction"].value_counts()

prediction
A4C          3167729
PLAX         2529914
Exclude      2179938
PSAX-AV      1893286
A2C          1603746
TEE          1553356
PSAX-PM      1305956
Subcostal    1299466
A3C          1092423
A5C           687503
PSAX-MV       356119
PSAX-AP       352876
SSN           213917
                 115
Name: count, dtype: int64

# Syngo

In [9]:
data_dir = 'data/dataset/Lee_Echo_Syngo'
adler = pd.read_csv(os.path.join(data_dir, 'Adler.csv'))
analytics_report = pd.read_csv(os.path.join(data_dir, 'Analytics_Report.csv'))
analytics_study = pd.read_csv(os.path.join(data_dir, 'AnalyticsStudy.csv'))
department = pd.read_csv(os.path.join(data_dir, 'Department.csv'))
field_map = pd.read_csv(os.path.join(data_dir, 'FieldMap.csv'))
measurement_type = pd.read_csv(os.path.join(data_dir, 'MeasurementType.csv'))
modalities = pd.read_csv(os.path.join(data_dir, 'Modalities.csv'))
observations = pd.read_csv(os.path.join(data_dir, 'Observations.csv'))
study_details = pd.read_csv(os.path.join(data_dir, 'StudyDetails.csv'))

/tmp/ipykernel_214/1852141919.py:3: DtypeWarning: Columns (18,19,23,24,36,37) have mixed types. Specify dtype option on import or set low_memory=False.
  analytics_report = pd.read_csv(os.path.join(data_dir, 'Analytics_Report.csv'))
/tmp/ipykernel_214/1852141919.py:10: DtypeWarning: Columns (6,7,8,16) have mixed types. Specify dtype option on import or set low_memory=False.
  study_details = pd.read_csv(os.path.join(data_dir, 'StudyDetails.csv'))

In [10]:
aws_uhn = pd.read_csv('aws/aws_uhn.csv', index_col=0)
print(aws_uhn.shape)

(320854, 9)

In [11]:
data_dir = 'data/dataset/Lee_Syngo_AnalyticMeasurement'
analytics_measure = pd.read_csv(os.path.join(data_dir, 'AnalyticsMeasure_Total.csv'))

In [12]:
analytics_measure.head()

,StudyRef,MeasurementTypeRef,MeasurementName,Value,Units
0,1000710,126,Height,189.000000,cm
1,1000710,127,Weight,97.300000,kg
2,1000710,140,Regenerate Study Structured Report,1.000000,unitless
3,1000710,10650,Stress Data Persisted,1.000000,unitless
4,1000710,13019,BSA (Boyd),2.265217,m2

In [13]:
len(analytics_measure)

26128284

In [20]:
syn_rvsp = analytics_measure.loc[analytics_measure['MeasurementName'] == 'RVSP (TR)']

In [21]:
print(len(syn_rvsp))
syn_rvsp.head()

62392

      StudyRef  MeasurementTypeRef MeasurementName      Value Units
59     1000712               11734       RVSP (TR)  20.757198  mmHg
892    1000731               11734       RVSP (TR)  31.040000  mmHg
1502   1000735               11734       RVSP (TR)  46.688400  mmHg
1807   1000750               11734       RVSP (TR)  91.908164  mmHg
1913   1000751               11734       RVSP (TR)  89.995600  mmHg

In [22]:
syn_df = syn_rvsp

In [23]:
# Create a boolean mask to identify matching StudyRef values
matching_mask = syn_df['StudyRef'].isin(aws_uhn['STUDY_REF'])

# Count the number of matches (True values)
number_of_matches = matching_mask.sum()

# Get the total number of unique studies in mv_obs for context
total_unique_studies = syn_df['StudyRef'].nunique()

print(f"\nTotal unique StudyRef values in syn_df: {total_unique_studies}")
print(f"Number of 'StudyRef' values from syn_df that are in aws_uhn: {number_of_matches}")
print(f"Percentage of matching studies: {(number_of_matches / total_unique_studies) * 100:.2f}%")

Total unique StudyRef values in syn_df: 62391
Number of 'StudyRef' values from syn_df that are in aws_uhn: 32317
Percentage of matching studies: 51.80%

In [24]:
import pandas as pd

# Step 1: Merge the two DataFrames
# We'll merge 'syn_df' (lvef) with 'aws_uhn' using 'StudyRef' and 'STUDY_REF' as the keys.
merged_df = pd.merge(syn_df, aws_uhn, left_on='StudyRef', right_on='STUDY_REF', how='inner')

# Step 2: Define the desired columns in the correct order
final_columns = [
    'STUDY_REF',
    's3_key',
    'Value',
    'PATIENT_ID',
    'STUDY_DATE',
    'STUDY_TIME',
    'DeidentifiedStudyID',
    'OriginalStudyID'
]

# # Step 3: Create the new table with only the specified columns
syn_df_labels = merged_df[final_columns]

# convert numeric date to datetime
syn_df_labels['STUDY_DATE'] = pd.to_datetime(
    syn_df_labels['STUDY_DATE'].astype(str), 
    format='%Y%m%d'
)

# now sortable by date
syn_df_labels = syn_df_labels.sort_values('STUDY_DATE')
syn_df_labels['STUDY_DATE'] = syn_df_labels['STUDY_DATE'].dt.strftime('%Y-%m-%d')

/tmp/ipykernel_214/2188486175.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  syn_df_labels['STUDY_DATE'] = pd.to_datetime(

In [25]:
len(syn_df_labels)

32831

In [26]:
syn_df_labels.head()

,STUDY_REF,s3_key,Value,PATIENT_ID,STUDY_DATE,STUDY_TIME,DeidentifiedStudyID,OriginalStudyID
5153,1330200,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715/,19.000000,002240,2007-06-06,115409.0,1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715,1.2.840.113663.1500.1.218885804.1.1.20070606.115409.484
16800,1607912,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703738552.20569141/,45.283600,N000122326,2008-08-06,92821.0,1.2.276.0.7230010.3.1.2.1714512485.1.1703738552.20569141,1.2.840.113696.452920.500.1017323.20080806093017
14896,1594868,echo-study/1.2.276.0.7230010.3.1.2.811753780.1.1703738554.17156032/,35.410021,N000479114,2012-11-26,85414.0,1.2.276.0.7230010.3.1.2.811753780.1.1703738554.17156032,1.2.840.113696.452920.500.2215232.20121127091148
25390,1665870,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426/,31.134853,N000040951,2013-01-22,144746.0,1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426,1.2.840.113696.452920.500.2296413.20130122142033
1570,1010410,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703409929.16860115/,30.000000,9430,2014-01-16,155756.0,1.2.276.0.7230010.3.1.2.1714512485.1.1703409929.16860115,1.2.840.113663.1500.1.193740021.1.1.20140116.155756.937

In [53]:
# specific to your dataframe variable
nan_count = syn_df_labels['Value'].isna().sum()

print(nan_count)

0

#### **To Do: Link to highest confidence + b/w A4C video in each study (maybe multiple, above a threshold). Do a patient-disjoint temporal split. Normalize regression values. Do the same for HeartLab.**

# HeartLab

In [27]:
data_dir = 'data/dataset'

msmt_defs = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_DEFINITIONS.csv'))
msmt_formula = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_FORMULA.csv'))
msmt_groups = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_GROUPS.csv'))
msmt_intersects = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_INTERSECTS.csv'))
msmt_lists = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_LISTS.csv'))
msmt = pd.read_csv(os.path.join(data_dir,'MEASUREMENTS.csv'))

findings = pd.read_csv(os.path.join(data_dir,'ENCOADMIN_FINDINGS.csv'))
finding_groups = pd.read_csv(os.path.join(data_dir,'ENCOADMIN_FINDING_GROUPS.csv'))
finding_intersects = pd.read_csv(os.path.join(data_dir,'ENCOADMIN_FINDING_INTERSECTS.csv'))

patients = pd.read_csv(os.path.join(data_dir,'Patients_No_PHI.csv'))
reports = pd.read_csv(os.path.join(data_dir,'REPORTS.csv'))
series = pd.read_csv(os.path.join(data_dir,'SERIES.csv'))
studies = pd.read_csv(os.path.join(data_dir,'STUDIES.csv'))

/tmp/ipykernel_214/2801898404.py:6: DtypeWarning: Columns (7,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  msmt_intersects = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_INTERSECTS.csv'))
/tmp/ipykernel_214/2801898404.py:15: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  reports = pd.read_csv(os.path.join(data_dir,'REPORTS.csv'))
/tmp/ipykernel_214/2801898404.py:16: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  series = pd.read_csv(os.path.join(data_dir,'SERIES.csv'))
/tmp/ipykernel_214/2801898404.py:17: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  studies = pd.read_csv(os.path.join(data_dir,'STUDIES.csv'))

In [28]:
hl_link = pd.read_csv(os.path.join(data_dir, 'heartlab_rep_study_video.csv'))

In [29]:
aws_heartlab = pd.read_csv('aws/aws_heartlab_0806.csv', index_col=0)
print(aws_heartlab.shape)

(215113, 12)

In [30]:
msmt.head()

,ID,NAME,FLAG,ACC_ID,HLCODE,STS_ID,TREND
0,8553,LAdDiam_MM,p,NaN,LAdDiam_MM,NaN,NaN
1,8554,LADiam_MM_AP,p,NaN,LADiam_MM_AP,NaN,NaN
2,8555,LADim_2D,p,NaN,LADim_2D,NaN,NaN
3,8556,LADim_MM,p,NaN,LADim_MM,NaN,NaN
4,8557,LADim_MM_Index_metric,p,NaN,LADim_MM_Index_metric,NaN,NaN

In [31]:
msmt_intersects.head()

,ID,REP_ID,MEAS_ID,PHAS_ID,VALUE,FIN_INT_ID,SEQ,SOURCE,OBSE_ID,GRAPH_FLAG,TREND,CALC_MODE,MEAS_PREFERENCE
0,8138913,351677,100229,1,56.00,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
1,8138914,351677,100156,1,24.06,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
2,8138915,351677,100255,1,21.46,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
3,8138916,351677,100688,1,29.60,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN
4,8138917,351677,100456,1,29.60,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN

In [32]:
msmt_intersects = msmt_intersects.merge(
    msmt[['ID', 'HLCODE']], 
    left_on='MEAS_ID', 
    right_on='ID', 
    how='left'
).drop(columns='ID_y').rename(columns={'ID_x': 'ID'})

In [33]:
msmt_intersects.head()

,ID,REP_ID,MEAS_ID,PHAS_ID,VALUE,FIN_INT_ID,SEQ,SOURCE,OBSE_ID,GRAPH_FLAG,TREND,CALC_MODE,MEAS_PREFERENCE,HLCODE
0,8138913,351677,100229,1,56.00,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,EF_Teich_2D
1,8138914,351677,100156,1,24.06,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,LV_E_EPRIME_LAT_RATIO
2,8138915,351677,100255,1,21.46,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,LV_E_EPRIME_SEP_RATIO
3,8138916,351677,100688,1,29.60,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,LVFS_CUBE_2D
4,8138917,351677,100456,1,29.60,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,LVFS_TEICH_2D

In [36]:
hl_rvsp = msmt_intersects.loc[msmt_intersects['HLCODE'] == 'RVSP']

In [37]:
print(len(hl_rvsp))
hl_rvsp.head()

24696

,ID,REP_ID,MEAS_ID,PHAS_ID,VALUE,FIN_INT_ID,SEQ,SOURCE,OBSE_ID,GRAPH_FLAG,TREND,CALC_MODE,MEAS_PREFERENCE,HLCODE
36,8322526,354905,100449,1,35.0,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,RVSP
201,7582004,341475,100449,1,63.0,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,RVSP
246,7582108,341474,100449,1,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RVSP
266,7582302,341468,100449,1,23.0,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,RVSP
371,7591773,341634,100449,1,34.0,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,RVSP

In [43]:
# Grab columns from the hl_link dataframes using REP_IDs
hl_link = pd.read_csv(os.path.join(data_dir, 'heartlab_rep_study_video.csv'))
# hl_df_labels = hl_link[hl_link['REP_ID'].isin(hl_ids)].copy()
hl_df = hl_rvsp

# REP_IDs that appear in the hl_df dataframe
hl_ids = hl_df['REP_ID'].dropna().unique()
print(len(hl_ids))

# Grab columns from the hl_link dataframes using REP_IDs
hl_df_labels = hl_link[hl_link['REP_ID'].isin(hl_ids)].copy()

24672

In [44]:
hl_df_labels = hl_df.merge(
    hl_df_labels,
    on='REP_ID',
    how='inner',
    suffixes=('', '_drop')  # keep REP_ID as-is, add suffix to duplicates
)

# Remove the duplicate REP_ID column if created
if 'REP_ID_drop' in hl_df_labels.columns:
    hl_df_labels = hl_df_labels.drop(columns=['REP_ID_drop'])

hl_df_labels = hl_df_labels.merge(
    aws_heartlab[['OriginalStudyID', 's3_key']],  # only needed columns
    on='OriginalStudyID',
    how='left'
)

hl_df_labels = hl_df_labels.dropna(subset=['s3_key'])

# convert STUDY_DATE to datetime objects
hl_df_labels['STUDY_DATE'] = pd.to_datetime(
    hl_df_labels['STUDY_DATE'], 
    format='%m/%d/%y %H:%M:%S'  # matches "01/20/09 10:29:09"
)



# now you can sort
hl_df_labels = hl_df_labels.sort_values('STUDY_DATE')
hl_df_labels['STUDY_DATE'] = hl_df_labels['STUDY_DATE'].dt.strftime('%Y-%m-%d')

hl_df_labels = hl_df_labels.rename(
    columns={'OriginalPatientID': 'PATIENT_ID'}
)

print(hl_df_labels.columns)
print(hl_df_labels.shape)
display(hl_df_labels.head())

Index(['ID', 'REP_ID', 'MEAS_ID', 'PHAS_ID', 'VALUE', 'FIN_INT_ID', 'SEQ',
       'SOURCE', 'OBSE_ID', 'GRAPH_FLAG', 'TREND', 'CALC_MODE',
       'MEAS_PREFERENCE', 'HLCODE', 'OriginalStudyID', 'PATIENT_ID',
       'DeidentifiedStudyID', 'DeidentifiedPatientID', 'STUDY_DATE',
       'STUDY_ID', 'SERI_ID', 'STUDY_INSTANCE_UID', 's3_key'],
      dtype='object')
(21711, 23)

,ID,REP_ID,MEAS_ID,PHAS_ID,VALUE,FIN_INT_ID,SEQ,SOURCE,OBSE_ID,GRAPH_FLAG,TREND,CALC_MODE,MEAS_PREFERENCE,HLCODE,OriginalStudyID,PATIENT_ID,DeidentifiedStudyID,DeidentifiedPatientID,STUDY_DATE,STUDY_ID,SERI_ID,STUDY_INSTANCE_UID,s3_key
472,7650479,342485,100449,1,65.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RVSP,1.2.840.113619.2.298.30002.1389344214.0.2,00000000,1.2.276.0.7230010.3.1.2.1714578744.1.1703362131.12671792,6d63bebe-0c41-4d78-882d-38182ef481f8,2014-01-10,385177,816494,1.2.840.113619.2.298.30002.1389344214.0.2,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703362131.12671792/
1307,7579130,340399,100449,1,28.0,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,RVSP,1.2.840.113663.1500.1.242451848.1.1.20140313.110838.734,1191618,1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101940,8bd65521-d857-4310-b117-b756fa151105,2014-03-13,393757,809123,1.2.840.113663.1500.1.242451848.1.1.20140313.110838.734,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101940/
56,7573071,340424,100449,1,26.0,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,RVSP,1.2.840.113663.1500.1.242451848.1.1.20140313.134501.453,3737291,1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101920,5add5c1c-af2e-415c-9e86-570dd3b3b040,2014-03-13,393794,809221,1.2.840.113663.1500.1.242451848.1.1.20140313.134501.453,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101920/
934,7647185,340893,100449,1,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,RVSP,1.3.12.2.1107.5.5.10.400319.30000014031907333250000000029,4154230,1.2.276.0.7230010.3.1.2.1714578744.1.1703751896.17303051,b428b240-fc44-4c8f-a084-7006b3ae2438,2014-03-19,394377,810704,1.3.12.2.1107.5.5.10.400319.30000014031907333250000000029,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703751896.17303051/
820,7572871,340963,100449,1,21.0,NaN,NaN,NaN,NaN,NaN,N,NaN,NaN,RVSP,1.2.124.113532.30763.51996.30715.20140320.90853.4787913,2333731,1.2.276.0.7230010.3.1.2.859333938.1.1703115125.8032174,39d47748-fe19-4d90-9bfd-d4565fbe5bdc,2014-03-20,397991,810944,1.2.124.113532.30763.51996.30715.20140320.90853.4787913,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703115125.8032174/

In [51]:
# specific to your dataframe variable
nan_count = hl_df_labels['VALUE'].isna().sum()

print(nan_count)

0

# Combine

In [62]:
label_col = 'Value'

In [63]:
# Columnsasciiant to keep
keep_cols = [
    'STUDY_REF','REP_ID','HLCODE', label_col ,'s3_key',  'STUDY_DATE',
    'STUDY_TIME', 'DeidentifiedStudyID', 'OriginalStudyID',
    'PATIENT_ID', 'DeidentifiedPatientID', 'SERI_ID', 'STUDY_ID',
    'STUDY_INSTANCE_UID'
]

# Rename 'VALUE' to 'Value' to match syn_df_labels
hl_df_labels = hl_df_labels.rename(columns={'VALUE': 'Value'})

# Combine both dataframes
uhn_df = pd.concat([syn_df_labels, hl_df_labels], ignore_index=True, sort=False)

# Drop overlapping OriginalStudyIDs (keep first occurrence)
uhn_df = uhn_df.drop_duplicates(subset='OriginalStudyID', keep='first')

# Restrict to selected columns
uhn_df = uhn_df.reindex(columns=keep_cols)

# Drop rows where there is no s3 key
uhn_df = uhn_df.dropna(subset=['s3_key'])

# Ensure STUDY_DATE is datetime before sorting
uhn_df['STUDY_DATE'] = pd.to_datetime(uhn_df['STUDY_DATE'], errors='coerce')

# Sort by STUDY_DATE (earliest first)
uhn_df = uhn_df.sort_values('STUDY_DATE')

print(uhn_df.shape)
display(uhn_df.head())

(54004, 14)

,STUDY_REF,REP_ID,HLCODE,Value,s3_key,STUDY_DATE,STUDY_TIME,DeidentifiedStudyID,OriginalStudyID,PATIENT_ID,DeidentifiedPatientID,SERI_ID,STUDY_ID,STUDY_INSTANCE_UID
0,1330200.0,NaN,NaN,19.000000,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715/,2007-06-06,115409.0,1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715,1.2.840.113663.1500.1.218885804.1.1.20070606.115409.484,002240,NaN,NaN,NaN,NaN
1,1607912.0,NaN,NaN,45.283600,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703738552.20569141/,2008-08-06,92821.0,1.2.276.0.7230010.3.1.2.1714512485.1.1703738552.20569141,1.2.840.113696.452920.500.1017323.20080806093017,N000122326,NaN,NaN,NaN,NaN
2,1594868.0,NaN,NaN,35.410021,echo-study/1.2.276.0.7230010.3.1.2.811753780.1.1703738554.17156032/,2012-11-26,85414.0,1.2.276.0.7230010.3.1.2.811753780.1.1703738554.17156032,1.2.840.113696.452920.500.2215232.20121127091148,N000479114,NaN,NaN,NaN,NaN
3,1665870.0,NaN,NaN,31.134853,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426/,2013-01-22,144746.0,1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426,1.2.840.113696.452920.500.2296413.20130122142033,N000040951,NaN,NaN,NaN,NaN
32831,NaN,342485.0,RVSP,65.000000,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703362131.12671792/,2014-01-10,NaN,1.2.276.0.7230010.3.1.2.1714578744.1.1703362131.12671792,1.2.840.113619.2.298.30002.1389344214.0.2,00000000,6d63bebe-0c41-4d78-882d-38182ef481f8,816494.0,385177.0,1.2.840.113619.2.298.30002.1389344214.0.2

In [64]:
# specific to your dataframe variable
nan_count = uhn_df['Value'].isna().sum()

print(nan_count)

0

In [95]:
uhn_df = uhn_df.dropna(subset=["Value"])

print(uhn_df.shape)
display(uhn_df.head())

(54004, 14)

,STUDY_REF,REP_ID,HLCODE,Value,s3_key,STUDY_DATE,STUDY_TIME,DeidentifiedStudyID,OriginalStudyID,PATIENT_ID,DeidentifiedPatientID,SERI_ID,STUDY_ID,STUDY_INSTANCE_UID
0,1330200.0,NaN,NaN,19.000000,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715/,2007-06-06,115409.0,1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715,1.2.840.113663.1500.1.218885804.1.1.20070606.115409.484,002240,NaN,NaN,NaN,NaN
1,1607912.0,NaN,NaN,45.283600,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703738552.20569141/,2008-08-06,92821.0,1.2.276.0.7230010.3.1.2.1714512485.1.1703738552.20569141,1.2.840.113696.452920.500.1017323.20080806093017,N000122326,NaN,NaN,NaN,NaN
2,1594868.0,NaN,NaN,35.410021,echo-study/1.2.276.0.7230010.3.1.2.811753780.1.1703738554.17156032/,2012-11-26,85414.0,1.2.276.0.7230010.3.1.2.811753780.1.1703738554.17156032,1.2.840.113696.452920.500.2215232.20121127091148,N000479114,NaN,NaN,NaN,NaN
3,1665870.0,NaN,NaN,31.134853,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426/,2013-01-22,144746.0,1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426,1.2.840.113696.452920.500.2296413.20130122142033,N000040951,NaN,NaN,NaN,NaN
32831,NaN,342485.0,RVSP,65.000000,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703362131.12671792/,2014-01-10,NaN,1.2.276.0.7230010.3.1.2.1714578744.1.1703362131.12671792,1.2.840.113619.2.298.30002.1389344214.0.2,00000000,6d63bebe-0c41-4d78-882d-38182ef481f8,816494.0,385177.0,1.2.840.113619.2.298.30002.1389344214.0.2

In [101]:
# 1. Get the set of IDs found in the video list
video_ids = set(df_view['study_id_check'].unique())

# 2. Find IDs that are in the CSV but NOT in the video list
missing_ids = set(uhn_df['DeidentifiedStudyID']) - video_ids

print(f"Count of Missing IDs: {len(missing_ids)}")

if len(missing_ids) > 0:
    # 3. Pick one "Missing" ID to investigate
    sample_missing = list(missing_ids)[0]
    print(f"\nInvestigating Missing ID: {sample_missing}")
    
    # 4. Check the row in the CSV to see where it *thinks* the video is
    csv_row = uhn_df[uhn_df['DeidentifiedStudyID'] == sample_missing].iloc[0]
    print(f"CSV thinks the file is here: {csv_row['s3_key']}")
    
    # 5. Search for ANY partial match in the video dataframe
    # This checks if the ID is there but just formatted differently (e.g. part of the string)
    potential_matches = df_view[df_view['s3_uri'].astype(str).str.contains(sample_missing, regex=False)]
    
    if len(potential_matches) > 0:
        print("\nFOUND A MATCH! The ID exists but the parser failed.")
        print("Example Video Path:", potential_matches['s3_uri'].iloc[0])
        print("Extracted ID was:", potential_matches['study_id_check'].iloc[0])
    else:
        print("\nNO MATCH FOUND. This study is truly absent from your video dataframe.")

Count of Missing IDs: 29554

Investigating Missing ID: 1.2.276.0.7230010.3.1.2.1667523124.1.1724284620.846925
CSV thinks the file is here: echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1724284620.846925/

FOUND A MATCH! The ID exists but the parser failed.
Example Video Path: s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1724284620.846925/1.2.276.0.7230010.3.1.3.1667523124.1.1724284715.847191/1.2.276.0.7230010.3.1.4.1667523124.1.1724284978.847957.mp4
Extracted ID was: None

# Create Final DF

In [96]:
import pandas as pd

# ---------------------------------------------------------
# 1. Prepare the Video Metadata (The 18M Dataset)
# ---------------------------------------------------------

# Merge your view and color dataframes (assuming they align or merging on s3_uri)
# If they are already aligned by index, you can just concat. 
# Ideally, merge on s3_uri to be safe:
df_videos = pd.merge(df_view, df_color[['s3_uri', 'is_color']], on='s3_uri', how='inner')

# FILTER: Keep only Color videos and the two views we care about
df_relevant = df_videos[
    (df_videos['is_color'] == 'Yes') & 
    (df_videos['prediction'].isin(['A4C', 'PSAX-AV']))
].copy()

In [97]:
# ---------------------------------------------------------
# 2. Extract Matching Key (Study UID)
# ---------------------------------------------------------

# We need to extract the Study UID from the s3_uri to match 'uhn_df'.
# Looking at your screenshot: 
# s3_uri: ".../echo-study/1.2.276.0.7230010.../..."
# uhn_df['DeidentifiedStudyID']: "1.2.276.0.7230010..."

# This function splits the path and grabs the folder name which is the Study UID
def extract_study_id(uri):
    # Split by '/' and find the part after 'echo-study'
    parts = uri.split('/')
    try:
        # Assuming the structure is .../echo-study/<StudyUID>/<VideoFile>
        # Adjust index if your path structure is slightly different
        study_idx = parts.index('echo-study') + 1 
        return parts[study_idx]
    except (ValueError, IndexError):
        return None

df_relevant['match_id'] = df_relevant['s3_uri'].apply(extract_study_id)

In [98]:
# ---------------------------------------------------------
# 3. Find Highest Confidence Video per View per Study
# ---------------------------------------------------------

# Sort by Study, View, and Confidence (High to Low)
df_sorted = df_relevant.sort_values(by=['match_id', 'prediction', 'confidence'], ascending=[True, True, False])

# Group by Study and View, taking the first one (which is now the highest confidence)
df_best = df_sorted.groupby(['match_id', 'prediction']).head(1)

In [104]:
import pandas as pd

# ---------------------------------------------------------
# 1. The ROBUST ID Extractor
# ---------------------------------------------------------
def extract_study_id_robust(uri):
    # Split the path into parts
    parts = uri.split('/')
    
    # Iterate through parts to find the Study UID
    # We look for the part starting with '1.2.276' (UHN OID root)
    # This ignores whether it's in 'echo-study', 'echo-study-2', or anywhere else.
    for part in parts:
        if part.startswith('1.2.276'):
            return part
            
    return None

# ---------------------------------------------------------
# 2. Re-Run the Extraction & Matching
# ---------------------------------------------------------

# Apply the new extractor
df_view['match_id'] = df_view['s3_uri'].apply(extract_study_id_robust)

# Merge video data with color data
df_videos = pd.merge(df_view, df_color[['s3_uri', 'is_color']], on='s3_uri', how='inner')

# Filter for the relevant videos (Color + Correct Views)
df_relevant = df_videos[
    (df_videos['is_color'] == 'Yes') & 
    (df_videos['prediction'].isin(['A4C', 'PSAX-AV']))
].copy()

# Sort by Confidence (High -> Low) so we pick the best one
df_sorted = df_relevant.sort_values(by=['match_id', 'prediction', 'confidence'], ascending=[True, True, False])

# Keep only the single best video per view, per study
df_best = df_sorted.groupby(['match_id', 'prediction']).head(1)

# Pivot to Wide Format (One row per study)
df_pivot = df_best.pivot(index='match_id', columns='prediction', values='s3_uri').reset_index()
df_pivot.columns.name = None
df_pivot = df_pivot.rename(columns={'A4C': 'path_A4C', 'PSAX-AV': 'path_PSAX_AV'})

In [115]:
# Final Merge with Labels
final_df = pd.merge(
    uhn_df[['DeidentifiedStudyID', 'Value', 'PATIENT_ID', 'STUDY_DATE', 's3_key']], 
    df_pivot,
    left_on='DeidentifiedStudyID',
    right_on='match_id',
    how='inner'
)

# Clean up
final_df = final_df[['s3_key', 'DeidentifiedStudyID', 'PATIENT_ID', 'STUDY_DATE', 'path_A4C', 'path_PSAX_AV', 'Value']]

print(f"Original Match Count: ~24,132")
print(f"New Match Count:      {len(final_df)}")
print(final_df.head())

Original Match Count: ~24,132
New Match Count:      53013
                                                                 s3_key  \
0  echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715/
1   echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426/
2  echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703409929.16860115/
3  echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101940/
4  echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101920/

                                        DeidentifiedStudyID  PATIENT_ID  \
0  1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715      002240
1   1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426  N000040951
2  1.2.276.0.7230010.3.1.2.1714512485.1.1703409929.16860115        9430
3  1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101940     1191618
4  1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101920     3737291

  STUDY_DATE  \
0 2007-06-06
1 2013-01-22
2 2014-01-16
3 2014-03-13
4 2014-03-13

                                                                                                                                                                                                            path_A4C  \
0    s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715/1.2.276.0.7230010.3.1.3.845494328.1.1703425979.19600134/1.2.276.0.7230010.3.1.4.811753780.1.1703427233.13997253.mp4
1    s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426/1.2.276.0.7230010.3.1.3.859333938.1.1703738543.17253427/1.2.276.0.7230010.3.1.4.1714512485.1.1703739247.20586442.mp4
2   s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703409929.16860115/1.2.276.0.7230010.3.1.3.1714512485.1.1703409939.16860213/1.2.276.0.7230010.3.1.4.859333938.1.1703410605.13825276.mp4
3   s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101940/1.2.276.0.7230010.3.1.3.1714512485.1.1703428946.17101941/1.2.276.0.7230010.3.1.4.811753780.1.1703429487.14049365.mp4
4  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101920/1.2.276.0.7230010.3.1.3.1714512485.1.1703428946.17101921/1.2.276.0.7230010.3.1.4.1714578744.1.1703429339.13944227.mp4

                                                                                                                                                                                                       path_PSAX_AV  \
0  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715/1.2.276.0.7230010.3.1.3.845494328.1.1703425979.19600134/1.2.276.0.7230010.3.1.4.1714512485.1.1703426333.17041854.mp4
1    s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426/1.2.276.0.7230010.3.1.3.859333938.1.1703738543.17253427/1.2.276.0.7230010.3.1.4.859333938.1.1703738795.17261226.mp4
2  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703409929.16860115/1.2.276.0.7230010.3.1.3.1714512485.1.1703409939.16860213/1.2.276.0.7230010.3.1.4.845494328.1.1703410374.19434137.mp4
3  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101940/1.2.276.0.7230010.3.1.3.1714512485.1.1703428946.17101941/1.2.276.0.7230010.3.1.4.859333938.1.1703429194.14050169.mp4
4  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101920/1.2.276.0.7230010.3.1.3.1714512485.1.1703428946.17101921/1.2.276.0.7230010.3.1.4.845494328.1.1703429153.19667004.mp4

       Value
0  19.000000
1  31.134853
2  30.000000
3  28.000000
4  26.000000

In [106]:
# ---------------------------------------------------------
# Updated Diagnostic: The "Funnel Analysis" with Robust Parsing
# ---------------------------------------------------------

# 1. Total Labels Available
total_labels = len(uhn_df['DeidentifiedStudyID'].unique())
print(f"Total Labeled Studies: {total_labels}")

# 2. Total Studies in the Video Dataset (Raw)
# Apply the ROBUST extractor to the original unfiltered df_view
df_view['study_id_check'] = df_view['s3_uri'].apply(extract_study_id_robust)
total_video_studies = len(df_view['study_id_check'].unique())
print(f"Total Studies with ANY video: {total_video_studies}")

# 3. Intersection (Do we even have videos for all labels?)
# Use the robustly extracted IDs for the intersection
videos_with_labels = set(df_view['study_id_check']).intersection(set(uhn_df['DeidentifiedStudyID']))
print(f"Studies having BOTH labels and videos (before filtering): {len(videos_with_labels)}")

# 4. The "Color" Funnel
# We must also apply the robust extractor to df_color to match correctly
# (Assuming df_color has s3_uri)
df_color['study_id_check'] = df_color['s3_uri'].apply(extract_study_id_robust)
color_ids = df_color[df_color['is_color'] == 'Yes']['study_id_check'].unique()

valid_color_studies = videos_with_labels.intersection(set(color_ids))
print(f"Studies with valid Color Video: {len(valid_color_studies)}")

# 5. The "View" Funnel
# We use the robust IDs from df_view which we calculated in Step 2
view_ids = df_view[df_view['prediction'].isin(['A4C', 'PSAX-AV'])]['study_id_check'].unique()

valid_view_studies = valid_color_studies.intersection(set(view_ids))
print(f"Studies with Color AND Correct View (A4C/PSAX): {len(valid_view_studies)}")

Total Labeled Studies: 54004
Total Studies with ANY video: 319818
Studies having BOTH labels and videos (before filtering): 53711
Studies with valid Color Video: 53678
Studies with Color AND Correct View (A4C/PSAX): 53133

# Create Splits

In [116]:
import pandas as pd
import numpy as np

def create_patient_disjoint_temporal_split(df, 
                                           patient_col='PATIENT_ID', 
                                           time_col='STUDY_DATE', 
                                           ratios=[0.8, 0.1, 0.1]):
    """
    Splits dataframe strictly by patient, ordered by time, respecting data volume ratios.
    """
    # 1. Get unique patients with their temporal metadata and study volume
    patient_meta = df.groupby(patient_col).agg(
        last_study_date=(time_col, 'max'),
        study_count=('s3_key', 'count') # Or any non-null col
    ).reset_index()

    # 2. Sort patients by time (Temporal aspect)
    patient_meta = patient_meta.sort_values(by='last_study_date')

    # 3. Calculate cumulative counts to find split indices based on VOLUME (not just patient count)
    total_studies = len(df)
    patient_meta['cumulative_studies'] = patient_meta['study_count'].cumsum()
    
    # Define thresholds
    train_cutoff = total_studies * ratios[0]
    val_cutoff = total_studies * (ratios[0] + ratios[1])

    # 4. Assign split labels
    def get_split_label(cumulative_count):
        if cumulative_count <= train_cutoff:
            return 'train'
        elif cumulative_count <= val_cutoff:
            return 'val'
        else:
            return 'test'

    patient_meta['split'] = patient_meta['cumulative_studies'].apply(get_split_label)

    # 5. Merge split labels back to original dataframe
    df_split = df.merge(patient_meta[[patient_col, 'split']], on=patient_col, how='left')

    # Create the subsets
    train_df = df_split[df_split['split'] == 'train'].copy()
    val_df = df_split[df_split['split'] == 'val'].copy()
    test_df = df_split[df_split['split'] == 'test'].copy()

    return train_df, val_df, test_df

# --- Usage ---

# Ensure STUDY_DATE is datetime (looks like you did this in Image 3, but good to double check)
final_df['STUDY_DATE'] = pd.to_datetime(final_df['STUDY_DATE'])

train_df, val_df, test_df = create_patient_disjoint_temporal_split(final_df)

# --- Verification & Stats ---
print(f"Total Studies: {len(syn_df_labels)}")
print(f"Train: {len(train_df)} ({len(train_df)/len(uhn_df):.1%}) | Dates: {train_df['STUDY_DATE'].min().date()} to {train_df['STUDY_DATE'].max().date()}")
print(f"Val:   {len(val_df)} ({len(val_df)/len(uhn_df):.1%}) | Dates: {val_df['STUDY_DATE'].min().date()} to {val_df['STUDY_DATE'].max().date()}")
print(f"Test:  {len(test_df)} ({len(test_df)/len(uhn_df):.1%}) | Dates: {test_df['STUDY_DATE'].min().date()} to {test_df['STUDY_DATE'].max().date()}")

# Verify Patient Disjointness
train_pats = set(train_df['PATIENT_ID'])
val_pats = set(val_df['PATIENT_ID'])
test_pats = set(test_df['PATIENT_ID'])

assert len(train_pats.intersection(val_pats)) == 0, "Leakage between Train and Val!"
assert len(train_pats.intersection(test_pats)) == 0, "Leakage between Train and Test!"
assert len(val_pats.intersection(test_pats)) == 0,   "Leakage between Val and Test!"

print("\nSUCCESS: Splits are patient-disjoint and temporally ordered.")

Total Studies: 32831
Train: 42410 (78.5%) | Dates: 2007-06-06 to 2019-01-22
Val:   5300 (9.8%) | Dates: 2014-03-20 to 2019-04-04
Test:  5303 (9.8%) | Dates: 2014-03-21 to 2019-05-27

SUCCESS: Splits are patient-disjoint and temporally ordered.

In [117]:
train_df.head()

,s3_key,DeidentifiedStudyID,PATIENT_ID,STUDY_DATE,path_A4C,path_PSAX_AV,Value,split
0,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715/,1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715,002240,2007-06-06,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715/1.2.276.0.7230010.3.1.3.845494328.1.1703425979.19600134/1.2.276.0.7230010.3.1.4.811753780.1.1703427233.13997253.mp4,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715/1.2.276.0.7230010.3.1.3.845494328.1.1703425979.19600134/1.2.276.0.7230010.3.1.4.1714512485.1.1703426333.17041854.mp4,19.000000,train
1,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426/,1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426,N000040951,2013-01-22,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426/1.2.276.0.7230010.3.1.3.859333938.1.1703738543.17253427/1.2.276.0.7230010.3.1.4.1714512485.1.1703739247.20586442.mp4,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426/1.2.276.0.7230010.3.1.3.859333938.1.1703738543.17253427/1.2.276.0.7230010.3.1.4.859333938.1.1703738795.17261226.mp4,31.134853,train
2,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703409929.16860115/,1.2.276.0.7230010.3.1.2.1714512485.1.1703409929.16860115,9430,2014-01-16,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703409929.16860115/1.2.276.0.7230010.3.1.3.1714512485.1.1703409939.16860213/1.2.276.0.7230010.3.1.4.859333938.1.1703410605.13825276.mp4,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703409929.16860115/1.2.276.0.7230010.3.1.3.1714512485.1.1703409939.16860213/1.2.276.0.7230010.3.1.4.845494328.1.1703410374.19434137.mp4,30.000000,train
3,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101940/,1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101940,1191618,2014-03-13,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101940/1.2.276.0.7230010.3.1.3.1714512485.1.1703428946.17101941/1.2.276.0.7230010.3.1.4.811753780.1.1703429487.14049365.mp4,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101940/1.2.276.0.7230010.3.1.3.1714512485.1.1703428946.17101941/1.2.276.0.7230010.3.1.4.859333938.1.1703429194.14050169.mp4,28.000000,train
4,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101920/,1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101920,3737291,2014-03-13,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101920/1.2.276.0.7230010.3.1.3.1714512485.1.1703428946.17101921/1.2.276.0.7230010.3.1.4.1714578744.1.1703429339.13944227.mp4,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101920/1.2.276.0.7230010.3.1.3.1714512485.1.1703428946.17101921/1.2.276.0.7230010.3.1.4.845494328.1.1703429153.19667004.mp4,26.000000,train

# Statistics

In [118]:
# 1. Clean the data (RVSP is usually 15-140 mmHg)
def clean_rvsp(df):
    initial_len = len(df)
    
    # RVSP PHYSIOLOGY BOUNDS
    # Min: 10 (Below this is likely an error or Mean Pressure)
    # Max: 170 (Eisenmenger syndrome/Severe PH can go >120. 100 is too low a cutoff.)
    df_clean = df[(df['Value'] >= 10) & (df['Value'] <= 170)].copy()
    
    dropped_count = initial_len - len(df_clean)
    if dropped_count > 0:
        print(f"Dropped {dropped_count} rows with invalid RVSP values (keeping 10-170 mmHg).")
        
    return df_clean

In [121]:
# 1. Create the simplified DataFrames
cols_to_keep = ['path_A4C', 'path_PSAX_AV', 'Value']

train_simple = train_df[cols_to_keep].copy()
val_simple = val_df[cols_to_keep].copy()
test_simple = test_df[cols_to_keep].copy()

# Apply the basic cleaning (removing negatives/impossible values)
train_clean = clean_rvsp(train_simple)
val_clean = clean_rvsp(val_simple)
test_clean = clean_rvsp(test_simple)

# 3. Function to print detailed statistics
def print_split_stats(name, df):
    print(f"================ {name} Set ================")
    print(f"Total Studies: {len(df)}")
    
    # Check for empty paths or null values
    missing_count = df.isnull().sum().sum()
    if missing_count > 0:
        print(f"WARNING: Found {missing_count} missing values!")
    
    # Calculate Skewness
    # RVSP is usually RIGHT skewed (Positive skew):
    # Most people are Normal (20-30), with a long tail of high pressure (PH).
    skewness = df['Value'].skew()
    
    stats = df['Value'].describe(percentiles=[0.05, 0.25, 0.5, 0.75, 0.95])
    
    print("\nTarget ('RVSP in mmHg') Statistics:")
    print(f"  Count: {int(stats['count'])}")
    print(f"  Mean:  {stats['mean']:.2f} mmHg")
    print(f"  Std:   {stats['std']:.2f}")
    print(f"  Skew:  {skewness:.2f} (expect > 0 for medical data)")
    print("-" * 20)
    print(f"  Min:   {stats['min']:.2f}")
    print(f"   5%:   {stats['5%']:.2f}  <-- Normal physiological low")
    print(f"  25%:   {stats['25%']:.2f}")
    print(f"  Median:{stats['50%']:.2f}  <-- Typical Healthy/Mild (~25-30)")
    print(f"  75%:   {stats['75%']:.2f}  <-- Likely Pulmonary Hypertension starts here")
    print(f"  95%:   {stats['95%']:.2f}  <-- Severe Pulmonary Hypertension")
    print(f"  Max:   {stats['max']:.2f}")
    print("\n")

# 4. Run the stats
print_split_stats("TRAIN", train_clean)
print_split_stats("VALIDATION", val_clean)
print_split_stats("TEST", test_clean)

Dropped 33 rows with invalid RVSP values (keeping 10-170 mmHg).
Dropped 2 rows with invalid RVSP values (keeping 10-170 mmHg).
Dropped 2 rows with invalid RVSP values (keeping 10-170 mmHg).
================ TRAIN Set ================
Total Studies: 42377
WARNING: Found 1408 missing values!

Target ('RVSP in mmHg') Statistics:
  Count: 42377
  Mean:  34.47 mmHg
  Std:   14.01
  Skew:  1.99 (expect > 0 for medical data)
--------------------
  Min:   10.00
   5%:   19.97  <-- Normal physiological low
  25%:   25.00
  Median:31.00  <-- Typical Healthy/Mild (~25-30)
  75%:   39.63  <-- Likely Pulmonary Hypertension starts here
  95%:   62.00  <-- Severe Pulmonary Hypertension
  Max:   164.00


================ VALIDATION Set ================
Total Studies: 5298
WARNING: Found 196 missing values!

Target ('RVSP in mmHg') Statistics:
  Count: 5298
  Mean:  36.66 mmHg
  Std:   15.44
  Skew:  1.93 (expect > 0 for medical data)
--------------------
  Min:   10.95
   5%:   20.54  <-- Normal physiological low
  25%:   26.14
  Median:32.84  <-- Typical Healthy/Mild (~25-30)
  75%:   42.04  <-- Likely Pulmonary Hypertension starts here
  95%:   66.84  <-- Severe Pulmonary Hypertension
  Max:   148.90


================ TEST Set ================
Total Studies: 5301
WARNING: Found 198 missing values!

Target ('RVSP in mmHg') Statistics:
  Count: 5301
  Mean:  36.62 mmHg
  Std:   15.51
  Skew:  2.00 (expect > 0 for medical data)
--------------------
  Min:   13.10
   5%:   20.31  <-- Normal physiological low
  25%:   26.07
  Median:32.85  <-- Typical Healthy/Mild (~25-30)
  75%:   42.06  <-- Likely Pulmonary Hypertension starts here
  95%:   66.84  <-- Severe Pulmonary Hypertension
  Max:   153.80

# Convert to V-JEPA Format

In [122]:
train_clean.head()

,path_A4C,path_PSAX_AV,Value
0,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715/1.2.276.0.7230010.3.1.3.845494328.1.1703425979.19600134/1.2.276.0.7230010.3.1.4.811753780.1.1703427233.13997253.mp4,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703425964.17035715/1.2.276.0.7230010.3.1.3.845494328.1.1703425979.19600134/1.2.276.0.7230010.3.1.4.1714512485.1.1703426333.17041854.mp4,19.000000
1,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426/1.2.276.0.7230010.3.1.3.859333938.1.1703738543.17253427/1.2.276.0.7230010.3.1.4.1714512485.1.1703739247.20586442.mp4,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703738543.17253426/1.2.276.0.7230010.3.1.3.859333938.1.1703738543.17253427/1.2.276.0.7230010.3.1.4.859333938.1.1703738795.17261226.mp4,31.134853
2,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703409929.16860115/1.2.276.0.7230010.3.1.3.1714512485.1.1703409939.16860213/1.2.276.0.7230010.3.1.4.859333938.1.1703410605.13825276.mp4,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703409929.16860115/1.2.276.0.7230010.3.1.3.1714512485.1.1703409939.16860213/1.2.276.0.7230010.3.1.4.845494328.1.1703410374.19434137.mp4,30.000000
3,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101940/1.2.276.0.7230010.3.1.3.1714512485.1.1703428946.17101941/1.2.276.0.7230010.3.1.4.811753780.1.1703429487.14049365.mp4,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101940/1.2.276.0.7230010.3.1.3.1714512485.1.1703428946.17101941/1.2.276.0.7230010.3.1.4.859333938.1.1703429194.14050169.mp4,28.000000
4,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101920/1.2.276.0.7230010.3.1.3.1714512485.1.1703428946.17101921/1.2.276.0.7230010.3.1.4.1714578744.1.1703429339.13944227.mp4,s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703428946.17101920/1.2.276.0.7230010.3.1.3.1714512485.1.1703428946.17101921/1.2.276.0.7230010.3.1.4.845494328.1.1703429153.19667004.mp4,26.000000

In [123]:
train_clean.columns

Index(['path_A4C', 'path_PSAX_AV', 'Value'], dtype='object')

In [125]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import pickle

# 1. Initialize the Scaler
scaler = StandardScaler()

# 2. Fit ONLY on the Training Set
# This learns the Mean (~35) and Std (~14) of your training data
train_values = train_clean['Value'].values.reshape(-1, 1)
scaler.fit(train_values)

print(f"RVSP Scaler fitted. Mean: {scaler.mean_[0]:.4f} mmHg, Std: {scaler.scale_[0]:.4f}")

# 3. Transform All Splits
# Creates 'norm_value' (e.g., 35mmHg -> 0.0, 65mmHg -> +2.1)
train_clean['norm_value'] = scaler.transform(train_clean['Value'].values.reshape(-1, 1))
val_clean['norm_value']   = scaler.transform(val_clean['Value'].values.reshape(-1, 1))
test_clean['norm_value']  = scaler.transform(test_clean['Value'].values.reshape(-1, 1))

# 4. Save the Scaler
# CRITICAL: Save as 'rvsp_scaler.pkl' so you don't overwrite your LVEF scaler
with open('rvsp_scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

# --- Verification ---
print("\nNormalization Check (Train Set):")
print(train_clean['norm_value'].describe())

print("\nExample Data (showing original mmHg and normalized Z-score):")
print(train_clean[['Value', 'norm_value']].head(3))

RVSP Scaler fitted. Mean: 34.4650 mmHg, Std: 14.0130

Normalization Check (Train Set):
count    4.237700e+04
mean     1.519106e-16
std      1.000012e+00
min     -1.745885e+00
25%     -6.754483e-01
50%     -2.472737e-01
75%      3.685396e-01
max      9.243931e+00
Name: norm_value, dtype: float64

Example Data (showing original mmHg and normalized Z-score):
       Value  norm_value
0  19.000000   -1.103623
1  31.134853   -0.237650
2  30.000000   -0.318636

In [128]:
import os
import pandas as pd

# 1. Define your output directory again
output_dir = 'csv'  # Or 'csv' depending on where you want them
os.makedirs(output_dir, exist_ok=True)

def write_strict_multiview_csv(df, filename):
    # 1. Drop rows where ANY of the required columns are NaN/None
    # This ensures every row has [A4C, PSAX, Label]
    df_clean = df.dropna(subset=['path_A4C', 'path_PSAX_AV', 'norm_value']).copy()
    
    dropped = len(df) - len(df_clean)
    if dropped > 0:
        print(f"⚠️  Dropped {dropped} incomplete rows from {filename} (missing one view).")
    
    output_path = os.path.join(output_dir, filename)
    
    # 2. Select columns
    export_df = df_clean[['path_A4C', 'path_PSAX_AV', 'norm_value']]
    
    # 3. Write to CSV with space delimiter
    export_df.to_csv(
        output_path, 
        sep=' ',       
        header=False,  
        index=False    
    )
    
    print(f"✅ Saved {len(export_df)} complete rows to: {output_path}")

# 2. Regenerate the CSVs
# (Assuming train_clean, val_clean, test_clean are still in memory. 
#  If not, reload them from your previous steps before running this.)

print("Regenerating cleaned CSVs...")
write_strict_multiview_csv(train_clean, 'rvsp_train.csv')
write_strict_multiview_csv(val_clean,   'rvsp_val.csv')
write_strict_multiview_csv(test_clean,  'rvsp_test.csv')

Regenerating cleaned CSVs...
⚠️  Dropped 1408 incomplete rows from rvsp_train.csv (missing one view).
✅ Saved 40969 complete rows to: csv/rvsp_train.csv
⚠️  Dropped 196 incomplete rows from rvsp_val.csv (missing one view).
✅ Saved 5102 complete rows to: csv/rvsp_val.csv
⚠️  Dropped 198 incomplete rows from rvsp_test.csv (missing one view).
✅ Saved 5103 complete rows to: csv/rvsp_test.csv