In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

import os

In [2]:
data_dir = '/cluster/projects/bwanggroup/echo_reports/echo-reports/data/dataset/Lee_Echo_Syngo'
adler = pd.read_csv(os.path.join(data_dir, 'Adler.csv'))
analytics_report = pd.read_csv(os.path.join(data_dir, 'Analytics_Report.csv'))
analytics_study = pd.read_csv(os.path.join(data_dir, 'AnalyticsStudy.csv'))
department = pd.read_csv(os.path.join(data_dir, 'Department.csv'))
field_map = pd.read_csv(os.path.join(data_dir, 'FieldMap.csv'))
measurement_type = pd.read_csv(os.path.join(data_dir, 'MeasurementType.csv'))
modalities = pd.read_csv(os.path.join(data_dir, 'Modalities.csv'))
observations = pd.read_csv(os.path.join(data_dir, 'Observations.csv'))
study_details = pd.read_csv(os.path.join(data_dir, 'StudyDetails.csv'))

/tmp/ipykernel_1443910/3515026001.py:3: DtypeWarning: Columns (18,19,23,24,36,37) have mixed types. Specify dtype option on import or set low_memory=False.
  analytics_report = pd.read_csv(os.path.join(data_dir, 'Analytics_Report.csv'))
/tmp/ipykernel_1443910/3515026001.py:10: DtypeWarning: Columns (6,7,8,16) have mixed types. Specify dtype option on import or set low_memory=False.
  study_details = pd.read_csv(os.path.join(data_dir, 'StudyDetails.csv'))

In [3]:
aws_uhn = pd.read_csv('/cluster/projects/bwanggroup/alif/home_projects_v2/aws/aws_uhn.csv', index_col=0)
print(aws_uhn.shape)

(320854, 9)

In [4]:
len(observations)

6577032

In [5]:
observations.head()

   StudyRef  ObservationID   Value    Type                         Name
0   1000750              9      _2   OTHER      EF_4CH_out_of_range_obs
1   1000750             10      _2   OTHER  EF_Biplane_out_of_range_obs
2   1000750             11  normal  NORMAL             LV_EF_2D-ASE_obs
3   1000750             12      _2   OTHER       EF_2D_out_of_range_obs
4   1000750             13  normal  NORMAL             LV_FS_2D-ASE_obs

# HeartLab

In [6]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

import os

In [7]:
data_dir = '/cluster/projects/bwanggroup/echo_reports/echo-reports/data/dataset'

msmt_defs = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_DEFINITIONS.csv'))
msmt_formula = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_FORMULA.csv'))
msmt_groups = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_GROUPS.csv'))
msmt_intersects = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_INTERSECTS.csv'))
msmt_lists = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_LISTS.csv'))
msmt = pd.read_csv(os.path.join(data_dir,'MEASUREMENTS.csv'))

findings = pd.read_csv(os.path.join(data_dir,'ENCOADMIN_FINDINGS.csv'))
finding_groups = pd.read_csv(os.path.join(data_dir,'ENCOADMIN_FINDING_GROUPS.csv'))
finding_intersects = pd.read_csv(os.path.join(data_dir,'ENCOADMIN_FINDING_INTERSECTS.csv'))

patients = pd.read_csv(os.path.join(data_dir,'Patients_No_PHI.csv'))
reports = pd.read_csv(os.path.join(data_dir,'REPORTS.csv'))
series = pd.read_csv(os.path.join(data_dir,'SERIES.csv'))
studies = pd.read_csv(os.path.join(data_dir,'STUDIES.csv'))

/tmp/ipykernel_1443910/92640382.py:6: DtypeWarning: Columns (7,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  msmt_intersects = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_INTERSECTS.csv'))
/tmp/ipykernel_1443910/92640382.py:15: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  reports = pd.read_csv(os.path.join(data_dir,'REPORTS.csv'))
/tmp/ipykernel_1443910/92640382.py:16: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  series = pd.read_csv(os.path.join(data_dir,'SERIES.csv'))
/tmp/ipykernel_1443910/92640382.py:17: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  studies = pd.read_csv(os.path.join(data_dir,'STUDIES.csv'))

In [8]:
hl_link = pd.read_csv('../heartlab_rep_study_video.csv')

In [9]:
print(len(hl_link))
hl_link.head()

196447

,OriginalStudyID,OriginalPatientID,DeidentifiedStudyID,DeidentifiedPatientID,SERI_ID,STUDY_ID,REP_ID,STUDY_INSTANCE_UID
0,1.2.124.113532.36.59504.16340.20101008.134646.290320,2566463,1.2.276.0.7230010.3.1.2.845494328.1.1703190346.14552982,847aa94b-235e-4b95-a8cd-098b14f5ed38,501919,256599,242059.0,1.2.124.113532.36.59504.16340.20101008.134646.290320
1,1.2.840.113619.2.185.2551.1239109659.0.3,3778399,1.2.276.0.7230010.3.1.2.859333938.1.1703353467.12454807,b5710e8c-fb6b-43b3-ae08-5ad07ef48376,383739,195252,192302.0,1.2.840.113619.2.185.2551.1239109659.0.3
2,1.3.12.2.1107.5.5.10.400111.30000013031207394725000000003,2084574,1.2.276.0.7230010.3.1.2.1714578744.1.1703743505.17198835,a0be47f9-fc3b-43a3-b22a-672a4426a904,715332,347756,311704.0,1.3.12.2.1107.5.5.10.400111.30000013031207394725000000003
3,1.2.840.113619.2.98.4671.1159859574.0.1268,2976665,1.2.276.0.7230010.3.1.2.859333938.1.1703375216.12991674,7c5babb0-3fc0-4b26-ba88-61b336fbc5f2,221150,102508,106628.0,1.2.840.113619.2.98.4671.1159859574.0.1268
4,1.2.840.113663.1500.1.323664363.1.1.20100118.130024.875,2351919,1.2.276.0.7230010.3.1.2.1714578744.1.1703514185.14878754,330bc9c9-50ed-43bc-a9f6-3daf2778ba24,439233,226079,217227.0,1.2.840.113663.1500.1.323664363.1.1.20100118.130024.875

In [10]:
aws_heartlab = pd.read_csv('/cluster/projects/bwanggroup/alif/home_projects_v2/aws/aws_heartlab_0806.csv', index_col=0)
print(aws_heartlab.shape)

(215113, 12)

In [11]:
finding_intersects = finding_intersects.merge(
    findings[['ID', 'HLCODE']], 
    left_on='FIN_ID', 
    right_on='ID', 
    how='left'
).drop(columns='ID_y').rename(columns={'ID_x': 'ID'})

# RA Size

In [32]:
syn_df = observations.loc[observations['Name'] == 'AoV_Regurgitation_obs']
syn_df = syn_df.dropna(subset=['Value'])

In [33]:
syn_df.head()

     StudyRef  ObservationID  Value   Type                   Name
102   1000846            172   none  OTHER  AoV_Regurgitation_obs
304   1000714            172  trace  OTHER  AoV_Regurgitation_obs
362   1000715            172   none  OTHER  AoV_Regurgitation_obs
411   1000730            172   none  OTHER  AoV_Regurgitation_obs
461   1000731            172  trace  OTHER  AoV_Regurgitation_obs

In [34]:
syn_df['Value'].value_counts()

Value
none                  49248
trace                 23365
mild                  13796
mild_to_moderate       2716
moderate               1672
severe                  753
moderate_to_severe      728
Name: count, dtype: int64

In [35]:
mapping_two = {
    'none': 'trivial',
    'trace': 'trivial',
    'mild': 'trivial',
    'mild_to_moderate': 'moderate_or_greater',
    'moderate': 'moderate_or_greater',
    'moderate_to_severe': 'moderate_or_greater',
    'severe': 'moderate_or_greater'
}

syn_df['Regurgitation_Binary'] = syn_df['Value'].map(mapping_two)

In [36]:
len(syn_df)

92278

In [37]:
syn_df['Regurgitation_Binary'].value_counts()

Regurgitation_Binary
trivial                86409
moderate_or_greater     5869
Name: count, dtype: int64

In [38]:
syn_df.head()

,StudyRef,ObservationID,Value,Type,Name,Regurgitation_Binary
102,1000846,172,none,OTHER,AoV_Regurgitation_obs,trivial
304,1000714,172,trace,OTHER,AoV_Regurgitation_obs,trivial
362,1000715,172,none,OTHER,AoV_Regurgitation_obs,trivial
411,1000730,172,none,OTHER,AoV_Regurgitation_obs,trivial
461,1000731,172,trace,OTHER,AoV_Regurgitation_obs,trivial

In [39]:
aws_uhn.columns

Index(['STUDY_REF', 'PATIENT_ID', 'STUDY_DATE', 'STUDY_TIME',
       'ACCESSION_NUMBER', 'OriginalStudyID', 'DeidentifiedStudyID', 's3_key',
       'study_dir'],
      dtype='object')

In [41]:
# Create a boolean mask to identify matching StudyRef values
matching_mask = syn_df['StudyRef'].isin(aws_uhn['STUDY_REF'])

# Count the number of matches (True values)
number_of_matches = matching_mask.sum()

# Get the total number of unique studies in mv_obs for context
total_unique_studies = syn_df['StudyRef'].nunique()

print(f"\nTotal unique StudyRef values in syn_df: {total_unique_studies}")
print(f"Number of 'StudyRef' values from syn_df that are in aws_uhn: {number_of_matches}")
print(f"Percentage of matching studies: {(number_of_matches / total_unique_studies) * 100:.2f}%")

Total unique StudyRef values in syn_df: 88643
Number of 'StudyRef' values from syn_df that are in aws_uhn: 44069
Percentage of matching studies: 49.72%

In [42]:
import pandas as pd

# Assuming 'mv_obs' and 'aws_uhn' are your DataFrames loaded as in the screenshots.

# Step 1: Merge the two DataFrames
# We'll merge 'mv_obs' with 'aws_uhn' using 'StudyRef' and 'STUDY_REF' as the keys.
merged_df = pd.merge(syn_df, aws_uhn, left_on='StudyRef', right_on='STUDY_REF', how='inner')

# Step 2: Define the desired columns in the correct order
final_columns = [
    'STUDY_REF',
    's3_key',
    'Value',
    'Regurgitation_Binary',
    'STUDY_DATE',
    'STUDY_TIME',
    'DeidentifiedStudyID',
    'OriginalStudyID'
]

# # Step 3: Create the new table with only the specified columns
syn_df_labels = merged_df[final_columns]

# replacement_map = {
#     'none': 'trace',
#     'moderate_to_severe': 'severe'
# }

# # Apply the replacement to the 'Value' column
# mvr_labels['Value'] = mvr_labels['Value'].replace(replacement_map)

In [43]:
print(syn_df_labels.shape)
print(syn_df_labels['Regurgitation_Binary'].value_counts())
print(syn_df_labels.columns)
display(syn_df_labels.head())

(44919, 8)
Regurgitation_Binary
trivial                41996
moderate_or_greater     2923
Name: count, dtype: int64
Index(['STUDY_REF', 's3_key', 'Value', 'Regurgitation_Binary', 'STUDY_DATE',
       'STUDY_TIME', 'DeidentifiedStudyID', 'OriginalStudyID'],
      dtype='object')

,STUDY_REF,s3_key,Value,Regurgitation_Binary,STUDY_DATE,STUDY_TIME,DeidentifiedStudyID,OriginalStudyID
0,1000846,echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1725195860.2750974/,none,trivial,20150722,93052.0,1.2.276.0.7230010.3.1.2.842097970.1.1725195860.2750974,1.3.12.2.1107.5.8.9.1002655211149138.20150722131319960
1,1000714,echo-study-2/1.2.276.0.7230010.3.1.2.895693665.1.1725195567.4281989/,trace,trivial,20150722,75829.0,1.2.276.0.7230010.3.1.2.895693665.1.1725195567.4281989,1.3.12.2.1107.5.8.9.1002655211149138.20150722115621748
2,1000715,echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725195606.3247721/,none,trivial,20150722,80330.0,1.2.276.0.7230010.3.1.2.895627313.1.1725195606.3247721,1.3.12.2.1107.5.8.9.1002655211149138.20150722120229265
3,1000730,echo-study-2/1.2.276.0.7230010.3.1.2.1714500150.1.1725195612.2220152/,none,trivial,20150722,80354.0,1.2.276.0.7230010.3.1.2.1714500150.1.1725195612.2220152,1.3.12.2.1107.5.8.9.1002655211149138.20150722120327219
4,1000731,echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1725195560.2343273/,trace,trivial,20150722,80649.0,1.2.276.0.7230010.3.1.2.1667523124.1.1725195560.2343273,1.3.12.2.1107.5.8.9.1002655211149138.20150722114847646

# Mitral Valve

In [48]:
codes = finding_intersects['HLCODE'].str.strip().str.lower()
hl_df = finding_intersects[codes.str.contains('tricuspid valve.*regurgitation', na=False)]
print(len(hl_mvr))
hl_df.head()

255590

,ID,FIN_ID,PHAS_ID,NOTE,SEQA_ID,SEQB_ID,SEQC_ID,REP_ID,SEQD_ID,STRUCTURE_GROUP_SEQ,HLCODE
2,6227,458,1,NaN,NaN,NaN,NaN,2028,NaN,NaN,tricuspid valve^function^regurgitation^mild to moderate
10,4009035,458,1,NaN,NaN,NaN,NaN,185500,NaN,NaN,tricuspid valve^function^regurgitation^mild to moderate
28,6255,456,1,NaN,NaN,NaN,NaN,2033,NaN,NaN,tricuspid valve^function^regurgitation^trace
62,4011715,457,1,NaN,NaN,NaN,NaN,185650,NaN,NaN,tricuspid valve^function^regurgitation^mild
65,4011728,457,1,NaN,NaN,NaN,NaN,185651,NaN,NaN,tricuspid valve^function^regurgitation^mild

In [49]:
hl_df['HLCODE'].value_counts()

HLCODE
tricuspid valve^function^regurgitation^trace                                                        131411
tricuspid valve^function^regurgitation^mild                                                          83130
tricuspid valve^function^regurgitation^mild to moderate                                              17188
tricuspid valve^function^regurgitation^moderate                                                      10270
tricuspid valve^function^regurgitation^no evidence of                                                 5671
tricuspid valve^function^regurgitation^moderate to severe                                             3993
tricuspid valve^function^regurgitation^severe                                                         3890
tricuspid valve^prosthetic^bioprosthetic function^prosthetic regurgitation                              19
local^tricuspid valve^prosthetic^bioprosthetic function^normal and physiologic regurgitation^494         7
right heart^tricuspid valve^doppler - regurgitation^trace                                                3
tricuspid valve^function^regurgitation^pisa                                                              2
tricuspid valve^prosthetic^bioprosthetic function^peri-prosthetic regurgitation                          2
right heart^tricuspid valve^doppler - regurgitation^moderate to severe(3+)                               1
right heart^tricuspid valve^doppler - regurgitation^peak gradient (mmhg)                                 1
right heart^tricuspid valve^doppler - regurgitation^mild(1+)                                             1
tricuspid valve^prosthetic^mechanical prosthetic function^prosthetic regurgitation                       1
Name: count, dtype: int64

In [50]:
keep = [
    "tricuspid valve^function^regurgitation^trace",
    "tricuspid valve^function^regurgitation^mild",
    "tricuspid valve^function^regurgitation^mild to moderate",
    "tricuspid valve^function^regurgitation^moderate",
    "tricuspid valve^function^regurgitation^no evidence of",
    "tricuspid valve^function^regurgitation^moderate to severe",
    "tricuspid valve^function^regurgitation^severe",
]

hl_df = hl_df[hl_df['HLCODE'].isin(keep)].copy()

In [53]:
mapping_two = {
    "tricuspid valve^function^regurgitation^no evidence of": "trivial",
    "tricuspid valve^function^regurgitation^trace": "trivial",
    "tricuspid valve^function^regurgitation^mild": "trivial",
    "tricuspid valve^function^regurgitation^mild to moderate": "trivial",
    "tricuspid valve^function^regurgitation^moderate": "moderate_or_greater",
    "tricuspid valve^function^regurgitation^moderate to severe": "moderate_or_greater",
    "tricuspid valve^function^regurgitation^severe": "moderate_or_greater",
}

hl_df['Regurgitation_Binary'] = hl_df['HLCODE'].map(mapping_two)

In [54]:
print(hl_df['Regurgitation_Binary'].dropna().value_counts())

Regurgitation_Binary
trivial                237400
moderate_or_greater     18153
Name: count, dtype: int64

In [55]:
# REP_IDs that appear in the pacemaker dataframe
hl_ids = hl_df['REP_ID'].dropna().unique()
print(len(hl_ids))

# Split hl_link into pacemaker / no-pacemaker subsets
hl_df_labels = hl_link[hl_link['REP_ID'].isin(hl_ids)].copy()

255506

In [56]:
hl_df_labels = hl_df.merge(
    hl_df_labels,
    on='REP_ID',
    how='inner',
    suffixes=('', '_drop')  # keep REP_ID as-is, add suffix to duplicates
)

# Remove the duplicate REP_ID column if created
if 'REP_ID_drop' in hl_df_labels.columns:
    hl_df_labels = hl_df_labels.drop(columns=['REP_ID_drop'])

print(hl_df_labels.columns)
print(hl_df_labels.shape)
display(hl_df_labels.head())

Index(['ID', 'FIN_ID', 'PHAS_ID', 'NOTE', 'SEQA_ID', 'SEQB_ID', 'SEQC_ID',
       'REP_ID', 'SEQD_ID', 'STRUCTURE_GROUP_SEQ', 'HLCODE',
       'Regurgitation_Binary', 'OriginalStudyID', 'OriginalPatientID',
       'DeidentifiedStudyID', 'DeidentifiedPatientID', 'SERI_ID', 'STUDY_ID',
       'STUDY_INSTANCE_UID'],
      dtype='object')
(176553, 19)

,ID,FIN_ID,PHAS_ID,NOTE,SEQA_ID,SEQB_ID,SEQC_ID,REP_ID,SEQD_ID,STRUCTURE_GROUP_SEQ,HLCODE,Regurgitation_Binary,OriginalStudyID,OriginalPatientID,DeidentifiedStudyID,DeidentifiedPatientID,SERI_ID,STUDY_ID,STUDY_INSTANCE_UID
0,4009035,458,1,NaN,NaN,NaN,NaN,185500,NaN,NaN,tricuspid valve^function^regurgitation^mild to moderate,trivial,1.2.124.113532.6.23355.16818.20090127.101618.4783525,2126381,1.2.276.0.7230010.3.1.2.1714578744.1.1703275050.10646188,ae6154bc-d23e-41d0-a5e3-141d81870b6d,370189,186986,1.2.124.113532.6.23355.16818.20090127.101618.4783525
1,4011715,457,1,NaN,NaN,NaN,NaN,185650,NaN,NaN,tricuspid valve^function^regurgitation^mild,trivial,1.2.124.113532.6.23355.16818.20090128.110409.4925290,3233033,1.2.276.0.7230010.3.1.2.859333938.1.1703275131.10724614,15bb3706-b59d-40c2-b4f9-9fa702f0b4ef,370473,187156,1.2.124.113532.6.23355.16818.20090128.110409.4925290
2,4011728,457,1,NaN,NaN,NaN,NaN,185651,NaN,NaN,tricuspid valve^function^regurgitation^mild,trivial,1.2.840.113663.1500.1.278589547.1.1.20090128.111412.93,3041728,1.2.276.0.7230010.3.1.2.1714578744.1.1703750152.17282140,9c4c5656-ce6f-4a34-868a-6a59c3dfbd1a,370474,187152,1.2.840.113663.1500.1.278589547.1.1.20090128.111412.93
3,4011756,457,1,NaN,NaN,NaN,NaN,185652,NaN,NaN,tricuspid valve^function^regurgitation^mild,trivial,1.2.840.113543.6.6.2.0.37283302253.20090128090756,3747295,1.2.276.0.7230010.3.1.2.1714578744.1.1703323089.11566575,18ffeead-0254-48d6-82df-b14054f6b145,370475,187101,1.2.840.113543.6.6.2.0.37283302253.20090128090756
4,4012757,455,1,NaN,NaN,NaN,NaN,185703,NaN,NaN,tricuspid valve^function^regurgitation^no evidence of,trivial,1.2.840.113619.2.185.2475.1233150619.0.2,1120926,1.2.276.0.7230010.3.1.2.859333938.1.1703347783.12184958,df01c3d2-1684-4951-ae6d-30b82cca719b,370578,187229,1.2.840.113619.2.185.2475.1233150619.0.2

In [60]:
hl_df_labels = hl_df_labels.merge(
    aws_heartlab[['OriginalStudyID', 's3_key']],  # only needed columns
    on='OriginalStudyID',
    how='left'
)

print(hl_df_labels.shape)
display(hl_df_labels.head())

(176567, 22)

,ID,FIN_ID,PHAS_ID,NOTE,SEQA_ID,SEQB_ID,SEQC_ID,REP_ID,SEQD_ID,STRUCTURE_GROUP_SEQ,HLCODE,Regurgitation_Binary,OriginalStudyID,OriginalPatientID,DeidentifiedStudyID,DeidentifiedPatientID,SERI_ID,STUDY_ID,STUDY_INSTANCE_UID,s3_key_x,s3_key_y,s3_key
0,4009035,458,1,NaN,NaN,NaN,NaN,185500,NaN,NaN,tricuspid valve^function^regurgitation^mild to moderate,trivial,1.2.124.113532.6.23355.16818.20090127.101618.4783525,2126381,1.2.276.0.7230010.3.1.2.1714578744.1.1703275050.10646188,ae6154bc-d23e-41d0-a5e3-141d81870b6d,370189,186986,1.2.124.113532.6.23355.16818.20090127.101618.4783525,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703275050.10646188/,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703275050.10646188/,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703275050.10646188/
1,4011715,457,1,NaN,NaN,NaN,NaN,185650,NaN,NaN,tricuspid valve^function^regurgitation^mild,trivial,1.2.124.113532.6.23355.16818.20090128.110409.4925290,3233033,1.2.276.0.7230010.3.1.2.859333938.1.1703275131.10724614,15bb3706-b59d-40c2-b4f9-9fa702f0b4ef,370473,187156,1.2.124.113532.6.23355.16818.20090128.110409.4925290,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703275131.10724614/,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703275131.10724614/,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703275131.10724614/
2,4011728,457,1,NaN,NaN,NaN,NaN,185651,NaN,NaN,tricuspid valve^function^regurgitation^mild,trivial,1.2.840.113663.1500.1.278589547.1.1.20090128.111412.93,3041728,1.2.276.0.7230010.3.1.2.1714578744.1.1703750152.17282140,9c4c5656-ce6f-4a34-868a-6a59c3dfbd1a,370474,187152,1.2.840.113663.1500.1.278589547.1.1.20090128.111412.93,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703750152.17282140/,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703750152.17282140/,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703750152.17282140/
3,4011756,457,1,NaN,NaN,NaN,NaN,185652,NaN,NaN,tricuspid valve^function^regurgitation^mild,trivial,1.2.840.113543.6.6.2.0.37283302253.20090128090756,3747295,1.2.276.0.7230010.3.1.2.1714578744.1.1703323089.11566575,18ffeead-0254-48d6-82df-b14054f6b145,370475,187101,1.2.840.113543.6.6.2.0.37283302253.20090128090756,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703323089.11566575/,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703323089.11566575/,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703323089.11566575/
4,4012757,455,1,NaN,NaN,NaN,NaN,185703,NaN,NaN,tricuspid valve^function^regurgitation^no evidence of,trivial,1.2.840.113619.2.185.2475.1233150619.0.2,1120926,1.2.276.0.7230010.3.1.2.859333938.1.1703347783.12184958,df01c3d2-1684-4951-ae6d-30b82cca719b,370578,187229,1.2.840.113619.2.185.2475.1233150619.0.2,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703347783.12184958/,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703347783.12184958/,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703347783.12184958/

In [61]:
hl_df_labels = hl_df_labels.dropna(subset=['s3_key'])

print(hl_df_labels.shape)
display(hl_df_labels.head())

(176567, 22)

,ID,FIN_ID,PHAS_ID,NOTE,SEQA_ID,SEQB_ID,SEQC_ID,REP_ID,SEQD_ID,STRUCTURE_GROUP_SEQ,HLCODE,Regurgitation_Binary,OriginalStudyID,OriginalPatientID,DeidentifiedStudyID,DeidentifiedPatientID,SERI_ID,STUDY_ID,STUDY_INSTANCE_UID,s3_key_x,s3_key_y,s3_key
0,4009035,458,1,NaN,NaN,NaN,NaN,185500,NaN,NaN,tricuspid valve^function^regurgitation^mild to moderate,trivial,1.2.124.113532.6.23355.16818.20090127.101618.4783525,2126381,1.2.276.0.7230010.3.1.2.1714578744.1.1703275050.10646188,ae6154bc-d23e-41d0-a5e3-141d81870b6d,370189,186986,1.2.124.113532.6.23355.16818.20090127.101618.4783525,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703275050.10646188/,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703275050.10646188/,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703275050.10646188/
1,4011715,457,1,NaN,NaN,NaN,NaN,185650,NaN,NaN,tricuspid valve^function^regurgitation^mild,trivial,1.2.124.113532.6.23355.16818.20090128.110409.4925290,3233033,1.2.276.0.7230010.3.1.2.859333938.1.1703275131.10724614,15bb3706-b59d-40c2-b4f9-9fa702f0b4ef,370473,187156,1.2.124.113532.6.23355.16818.20090128.110409.4925290,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703275131.10724614/,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703275131.10724614/,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703275131.10724614/
2,4011728,457,1,NaN,NaN,NaN,NaN,185651,NaN,NaN,tricuspid valve^function^regurgitation^mild,trivial,1.2.840.113663.1500.1.278589547.1.1.20090128.111412.93,3041728,1.2.276.0.7230010.3.1.2.1714578744.1.1703750152.17282140,9c4c5656-ce6f-4a34-868a-6a59c3dfbd1a,370474,187152,1.2.840.113663.1500.1.278589547.1.1.20090128.111412.93,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703750152.17282140/,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703750152.17282140/,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703750152.17282140/
3,4011756,457,1,NaN,NaN,NaN,NaN,185652,NaN,NaN,tricuspid valve^function^regurgitation^mild,trivial,1.2.840.113543.6.6.2.0.37283302253.20090128090756,3747295,1.2.276.0.7230010.3.1.2.1714578744.1.1703323089.11566575,18ffeead-0254-48d6-82df-b14054f6b145,370475,187101,1.2.840.113543.6.6.2.0.37283302253.20090128090756,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703323089.11566575/,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703323089.11566575/,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703323089.11566575/
4,4012757,455,1,NaN,NaN,NaN,NaN,185703,NaN,NaN,tricuspid valve^function^regurgitation^no evidence of,trivial,1.2.840.113619.2.185.2475.1233150619.0.2,1120926,1.2.276.0.7230010.3.1.2.859333938.1.1703347783.12184958,df01c3d2-1684-4951-ae6d-30b82cca719b,370578,187229,1.2.840.113619.2.185.2475.1233150619.0.2,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703347783.12184958/,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703347783.12184958/,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703347783.12184958/

# Combine

In [62]:
# Columns you want to keep
keep_cols = [
    'STUDY_REF','REP_ID','HLCODE', 'Value', 'Regurgitation_Binary','s3_key',  'STUDY_DATE',
    'STUDY_TIME', 'DeidentifiedStudyID', 'OriginalStudyID',
     
    'OriginalPatientID', 'DeidentifiedPatientID', 'SERI_ID', 'STUDY_ID',
    'STUDY_INSTANCE_UID'
]

# Combine both dataframes
uhn_df = pd.concat([syn_df_labels, hl_df_labels], ignore_index=True, sort=False)

# Drop overlapping OriginalStudyIDs (keep first occurrence)
uhn_df = uhn_df.drop_duplicates(subset='OriginalStudyID', keep='first')

# Restrict to selected columns (any missing columns will be added as NaN)
uhn_df = uhn_df.reindex(columns=keep_cols)

print(uhn_df.shape)
display(uhn_df.head())

(218800, 15)

,STUDY_REF,REP_ID,HLCODE,Value,Regurgitation_Binary,s3_key,STUDY_DATE,STUDY_TIME,DeidentifiedStudyID,OriginalStudyID,OriginalPatientID,DeidentifiedPatientID,SERI_ID,STUDY_ID,STUDY_INSTANCE_UID
0,1000846.0,NaN,NaN,none,trivial,echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1725195860.2750974/,20150722.0,93052.0,1.2.276.0.7230010.3.1.2.842097970.1.1725195860.2750974,1.3.12.2.1107.5.8.9.1002655211149138.20150722131319960,NaN,NaN,NaN,NaN,NaN
1,1000714.0,NaN,NaN,trace,trivial,echo-study-2/1.2.276.0.7230010.3.1.2.895693665.1.1725195567.4281989/,20150722.0,75829.0,1.2.276.0.7230010.3.1.2.895693665.1.1725195567.4281989,1.3.12.2.1107.5.8.9.1002655211149138.20150722115621748,NaN,NaN,NaN,NaN,NaN
2,1000715.0,NaN,NaN,none,trivial,echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725195606.3247721/,20150722.0,80330.0,1.2.276.0.7230010.3.1.2.895627313.1.1725195606.3247721,1.3.12.2.1107.5.8.9.1002655211149138.20150722120229265,NaN,NaN,NaN,NaN,NaN
3,1000730.0,NaN,NaN,none,trivial,echo-study-2/1.2.276.0.7230010.3.1.2.1714500150.1.1725195612.2220152/,20150722.0,80354.0,1.2.276.0.7230010.3.1.2.1714500150.1.1725195612.2220152,1.3.12.2.1107.5.8.9.1002655211149138.20150722120327219,NaN,NaN,NaN,NaN,NaN
4,1000731.0,NaN,NaN,trace,trivial,echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1725195560.2343273/,20150722.0,80649.0,1.2.276.0.7230010.3.1.2.1667523124.1.1725195560.2343273,1.3.12.2.1107.5.8.9.1002655211149138.20150722114847646,NaN,NaN,NaN,NaN,NaN

In [63]:
uhn_df = uhn_df.dropna(subset=['s3_key'])

print(uhn_df.shape)
display(uhn_df.head())

(218800, 15)

,STUDY_REF,REP_ID,HLCODE,Value,Regurgitation_Binary,s3_key,STUDY_DATE,STUDY_TIME,DeidentifiedStudyID,OriginalStudyID,OriginalPatientID,DeidentifiedPatientID,SERI_ID,STUDY_ID,STUDY_INSTANCE_UID
0,1000846.0,NaN,NaN,none,trivial,echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1725195860.2750974/,20150722.0,93052.0,1.2.276.0.7230010.3.1.2.842097970.1.1725195860.2750974,1.3.12.2.1107.5.8.9.1002655211149138.20150722131319960,NaN,NaN,NaN,NaN,NaN
1,1000714.0,NaN,NaN,trace,trivial,echo-study-2/1.2.276.0.7230010.3.1.2.895693665.1.1725195567.4281989/,20150722.0,75829.0,1.2.276.0.7230010.3.1.2.895693665.1.1725195567.4281989,1.3.12.2.1107.5.8.9.1002655211149138.20150722115621748,NaN,NaN,NaN,NaN,NaN
2,1000715.0,NaN,NaN,none,trivial,echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725195606.3247721/,20150722.0,80330.0,1.2.276.0.7230010.3.1.2.895627313.1.1725195606.3247721,1.3.12.2.1107.5.8.9.1002655211149138.20150722120229265,NaN,NaN,NaN,NaN,NaN
3,1000730.0,NaN,NaN,none,trivial,echo-study-2/1.2.276.0.7230010.3.1.2.1714500150.1.1725195612.2220152/,20150722.0,80354.0,1.2.276.0.7230010.3.1.2.1714500150.1.1725195612.2220152,1.3.12.2.1107.5.8.9.1002655211149138.20150722120327219,NaN,NaN,NaN,NaN,NaN
4,1000731.0,NaN,NaN,trace,trivial,echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1725195560.2343273/,20150722.0,80649.0,1.2.276.0.7230010.3.1.2.1667523124.1.1725195560.2343273,1.3.12.2.1107.5.8.9.1002655211149138.20150722114847646,NaN,NaN,NaN,NaN,NaN

In [64]:
uhn_df['Regurgitation_Binary'].value_counts()

Regurgitation_Binary
trivial                204315
moderate_or_greater     14485
Name: count, dtype: int64

In [65]:
uhn_df.to_csv('uhn_tvr_0912.csv')