# MULTI RV Fx

In [39]:
import pandas as pd

# Show all columns and don’t wrap onto multiple lines
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)

# Don’t truncate cell text
pd.set_option('display.max_colwidth', None)

# Rows: pick a high cap (avoid None on huge frames)
pd.set_option('display.max_rows', 200)   # or None to show all (can be slow)
pd.set_option('display.min_rows', 20)

# Let pandas auto-detect available width
pd.set_option('display.width', 0)

In [7]:
import pandas as pd
from pathlib import Path

all_es = pd.read_parquet('all_es_combined.parquet')

In [8]:
all_es.shape

(18111381, 17)

In [9]:
all_es.head()

,png_uri,mp4_uri,pred_view,quality,salience,p_a2c,p_a3c,p_a4c,p_a5c,p_plax,p_tee,p_exclude,p_psax-av,p_psax-mv,p_psax-ap,p_psax-pm,mp4_uri_corrected
0,s3://echodata25/results/echo-study/1.2.276.0.7...,s3://echodata25/results/echo-study/1.2.276.0.7...,exclude,0.042402,0.541041,0.000002,0.000120,0.000119,0.000952,0.222900,0.020416,0.754395,0.001119,0.000000,0.000137,0.000011,s3://echodata25/results/echo-study/1.2.276.0.7...
1,s3://echodata25/results/echo-study/1.2.276.0.7...,s3://echodata25/results/echo-study/1.2.276.0.7...,a2c,0.083963,0.576947,0.788086,0.080505,0.126953,0.000072,0.000019,0.002302,0.001903,0.000000,0.000000,0.000000,0.000000,s3://echodata25/results/echo-study/1.2.276.0.7...
2,s3://echodata25/results/echo-study/1.2.276.0.7...,s3://echodata25/results/echo-study/1.2.276.0.7...,tee,0.090764,0.362434,0.011147,0.000251,0.010651,0.000403,0.005856,0.478760,0.451660,0.000301,0.000902,0.012230,0.027878,s3://echodata25/results/echo-study/1.2.276.0.7...
3,s3://echodata25/results/echo-study/1.2.276.0.7...,s3://echodata25/results/echo-study/1.2.276.0.7...,a4c,0.062837,0.626273,0.094849,0.000040,0.867188,0.001674,0.000007,0.019531,0.016907,0.000000,0.000000,0.000000,0.000000,s3://echodata25/results/echo-study/1.2.276.0.7...
4,s3://echodata25/results/echo-study/1.2.276.0.7...,s3://echodata25/results/echo-study/1.2.276.0.7...,exclude,0.024978,0.703782,0.000076,0.000004,0.000198,0.003231,0.000531,0.001554,0.994629,0.000006,0.000000,0.000001,0.000000,s3://echodata25/results/echo-study/1.2.276.0.7...

In [10]:
# Create a new DataFrame called 'a4c_df' by filtering 'all_es'
# all_es = combined_df
# a4c_df = all_es[all_es['pred_view'] == 'a4c'].copy()

# This regex finds 'echo-study', 'echo-study-1', or 'echo-study-2',
# and then captures the sequence of characters that follows until the next slash.
regex_pattern = r'results/echo-study(?:-[12])?/([^/]+)'

# Use .str.extract() to pull out the captured group (the Study ID)
all_es['DeidentifiedStudyID'] = all_es['png_uri'].str.extract(regex_pattern)

all_es = all_es.rename(
    columns={'mp4_uri_corrected': 'URI'}
)

In [11]:
print(all_es.shape)
display(all_es.head())

(18111381, 18)

,png_uri,mp4_uri,pred_view,quality,salience,p_a2c,p_a3c,p_a4c,p_a5c,p_plax,p_tee,p_exclude,p_psax-av,p_psax-mv,p_psax-ap,p_psax-pm,URI,DeidentifiedStudyID
0,s3://echodata25/results/echo-study/1.2.276.0.7...,s3://echodata25/results/echo-study/1.2.276.0.7...,exclude,0.042402,0.541041,0.000002,0.000120,0.000119,0.000952,0.222900,0.020416,0.754395,0.001119,0.000000,0.000137,0.000011,s3://echodata25/results/echo-study/1.2.276.0.7...,1.2.276.0.7230010.3.1.2.1714512485.1.170311135...
1,s3://echodata25/results/echo-study/1.2.276.0.7...,s3://echodata25/results/echo-study/1.2.276.0.7...,a2c,0.083963,0.576947,0.788086,0.080505,0.126953,0.000072,0.000019,0.002302,0.001903,0.000000,0.000000,0.000000,0.000000,s3://echodata25/results/echo-study/1.2.276.0.7...,1.2.276.0.7230010.3.1.2.1714512485.1.170311135...
2,s3://echodata25/results/echo-study/1.2.276.0.7...,s3://echodata25/results/echo-study/1.2.276.0.7...,tee,0.090764,0.362434,0.011147,0.000251,0.010651,0.000403,0.005856,0.478760,0.451660,0.000301,0.000902,0.012230,0.027878,s3://echodata25/results/echo-study/1.2.276.0.7...,1.2.276.0.7230010.3.1.2.1714512485.1.170311135...
3,s3://echodata25/results/echo-study/1.2.276.0.7...,s3://echodata25/results/echo-study/1.2.276.0.7...,a4c,0.062837,0.626273,0.094849,0.000040,0.867188,0.001674,0.000007,0.019531,0.016907,0.000000,0.000000,0.000000,0.000000,s3://echodata25/results/echo-study/1.2.276.0.7...,1.2.276.0.7230010.3.1.2.1714512485.1.170311135...
4,s3://echodata25/results/echo-study/1.2.276.0.7...,s3://echodata25/results/echo-study/1.2.276.0.7...,exclude,0.024978,0.703782,0.000076,0.000004,0.000198,0.003231,0.000531,0.001554,0.994629,0.000006,0.000000,0.000001,0.000000,s3://echodata25/results/echo-study/1.2.276.0.7...,1.2.276.0.7230010.3.1.2.1714512485.1.170311135...

# Connect to Labels

In [14]:
rvfx_labels = pd.read_csv('csv/rvfx_labels.csv')

In [ ]:
# Select only the necessary columns from your labels DataFrame for efficiency
labels_to_merge = rvfx_labels[['DeidentifiedStudyID', 'Value']]

# Merge the two DataFrames to find the overlap and add the 'Value'
# 'how="inner"' ensures only matching DeidentifiedStudyIDs are kept
all_rvfx_labels = pd.merge(
    all_es, 
    labels_to_merge, 
    on='DeidentifiedStudyID', 
    how='inner'
)

In [47]:
print(f"Found {len(all_rvfx_labels)} overlapping studies.")
print(all_rvfx_labels.columns)
all_rvfx_labels.head()

Found 2998761 overlapping studies.
Index(['png_uri', 'mp4_uri', 'pred_view', 'quality', 'salience', 'p_a2c',
       'p_a3c', 'p_a4c', 'p_a5c', 'p_plax', 'p_tee', 'p_exclude', 'p_psax-av',
       'p_psax-mv', 'p_psax-ap', 'p_psax-pm', 'URI', 'DeidentifiedStudyID',
       'Value', 'Value_numeric'],
      dtype='object')

                                                                                                                                                                png_uri                                                                                                                                                  mp4_uri pred_view   quality  salience     p_a2c     p_a3c     p_a4c     p_a5c    p_plax     p_tee  p_exclude  p_psax-av  p_psax-mv  p_psax-ap  p_psax-pm                                                                                                                                                                                                               URI                                       DeidentifiedStudyID   Value  Value_numeric
0  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/unmasked/png/1.2.276.0.7230010.3.1.4.859333938.1.1703360325.12713648.png  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.4.859333938.1.1703360325.12713648.mp4      plax  0.161728  0.736507  0.000001  0.000006  0.000014  0.000001  0.982910  0.000089   0.017181   0.000000   0.000000   0.000000   0.000000  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.859333938.1.1703360325.12713648.mp4  1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239  normal              0
1  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/unmasked/png/1.2.276.0.7230010.3.1.4.845494328.1.1703360385.18288171.png  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.4.845494328.1.1703360385.18288171.mp4   exclude  0.057467  0.381254  0.029465  0.001394  0.001695  0.000169  0.441406  0.002899   0.520020   0.001324   0.000014   0.001257   0.000318  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.845494328.1.1703360385.18288171.mp4  1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239  normal              0
2  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/unmasked/png/1.2.276.0.7230010.3.1.4.859333938.1.1703361188.12739794.png  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.4.859333938.1.1703361188.12739794.mp4       a4c  0.092671  0.414520  0.000096  0.012268  0.552246  0.408691  0.000313  0.000596   0.025818   0.000017   0.000001   0.000004   0.000002  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.859333938.1.1703361188.12739794.mp4  1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239  normal              0
3  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/unmasked/png/1.2.276.0.7230010.3.1.4.845494328.1.1703361102.18310441.png  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.4.845494328.1.1703361102.18310441.mp4   exclude  0.080342  0.519220  0.000003  0.000001  0.000724  0.000024  0.000453  0.000322   0.707031   0.039276   0.021423   0.055389   0.175293  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.845494328.1.1703361102.18310441.mp4  1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147  normal              0
4  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/unmasked/png/1.2.276.0.7230010.3.1.4.811753780.1.1703361001.12780223.png  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.4.811753780.1.1703361001.12780223.mp4      plax  0.130656  0.726208  0.000000  0.000019  0.000006  0.000001  0.981445  0.000016   0.018478   0.000058   0.000000   0.000003   0.000002  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.811753780.1.1703361001.12780223.mp4  1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147  normal              0

In [21]:
label_names = 'multi_rvfx_labels'
all_rvfx_labels.to_csv(f"csv/{label_names}.csv")

# Multi CSV (Classes)

In [48]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

# ----- inputs -----
df = all_rvfx_labels.copy()  # your dataframe in the screenshot
label_names = "rvfx_labels"
N_VIEWS = 9  # you listed 9; we'll use your explicit order below

# canonical view order (8 or 9 — keep what you want)
CANONICAL_VIEWS = [
    "p_a2c", "p_a3c", "p_a4c", "p_a5c", "p_plax",
    "p_psax-av", "p_psax-mv", "p_psax-ap", "p_psax-pm"
]
# choose first 8 if you truly want 8:
# CANONICAL_VIEWS = CANONICAL_VIEWS[:8]

In [49]:
VIEW_PROB_COL = {v: v for v in CANONICAL_VIEWS}  # p_* columns already match
# URI_COL = "mp4_uri" if "mp4_uri" in df.columns else "URI"
URI_COL = "URI"
STUDY_COL = "DeidentifiedStudyID"
LABEL_COL = "Value"  # text label column
MISSING_TOKEN = "MISS"  # will be written in CSV for missing views

In [50]:
label_mapping = {"normal": 0, "reduced": 1}
df["label_int"] = df[LABEL_COL].map(label_mapping)
if df["label_int"].isna().any():
    raise ValueError(f"Unmapped labels: {df.loc[df['label_int'].isna(), LABEL_COL].unique().tolist()}")

In [51]:
# ----- per-study selection: take highest-confidence URI per view -----
def select_views_for_study(g: pd.DataFrame) -> pd.Series:
    out_paths = {}
    out_confs = {}
    for v in CANONICAL_VIEWS:
        pcol = VIEW_PROB_COL[v]
        # robust: ignore rows with missing/empty URI
        g_valid = g[g[URI_COL].astype(str).str.len() > 0].copy()
        if g_valid.empty or (pcol not in g_valid.columns):
            out_paths[v] = MISSING_TOKEN
            out_confs[v] = np.nan
            continue
        idx = g_valid[pcol].astype(float).idxmax()
        best_p = float(g_valid.loc[idx, pcol])
        best_uri = str(g_valid.loc[idx, URI_COL]) if best_p > 0 else MISSING_TOKEN
        out_paths[v] = best_uri
        out_confs[v] = best_p if best_uri != MISSING_TOKEN else np.nan

    # label: majority vote (mode) over the group
    label_mode = g["label_int"].mode()
    label_int = int(label_mode.iloc[0])

    # row that will be written to CSV (space-separated URIs in canonical order + label)
    csv_row = " ".join(out_paths[v] for v in CANONICAL_VIEWS) + f" {label_int}"

    # pack: one column per view path + label
    rec = {f"{v}": out_paths[v] for v in CANONICAL_VIEWS}
    rec["label"] = label_int
    rec["CSV_Row"] = csv_row
    # also include confidences for preview
    for v in CANONICAL_VIEWS:
        rec[f"conf_{v}"] = out_confs[v]
    return pd.Series(rec)

In [52]:
per_study = (
    df.groupby(STUDY_COL, sort=False, as_index=True)
      .apply(select_views_for_study)
)

# ----- preview table you asked for -----
preview_cols = [STUDY_COL, "CSV_Row"] + CANONICAL_VIEWS  # show chosen URIs per slot
conf_cols = [f"conf_{v}" for v in CANONICAL_VIEWS]
preview = per_study.reset_index()[[STUDY_COL, "CSV_Row", *conf_cols]]
print(preview.head())

                                        DeidentifiedStudyID                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         CSV_Row  conf_p_a2c  conf_p_a3c  conf_p_a4c  conf_p_a5c  conf_p_plax  conf_p_psax-av  conf_p_psax-mv  conf_p_psax-ap  conf_p_psax-pm
0  1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.1714512485.1.1703361101.15655449.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.1714578744.1.1703361154.12646028.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.1714512485.1.1703360773.15644824.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.1714512485.1.1703361209.15658939.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.845494328.1.1703360348.18286976.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.811753780.1.1703360512.12765587.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.859333938.1.1703360598.12722190.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.859333938.1.1703361288.12742938.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.859333938.1.1703360624.12723048.mp4 0    0.833496    0.985840    0.985840    0.426270     0.999023        0.997070        0.162964        0.978516        0.966309
1  1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.1714512485.1.1703361685.15674252.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.811753780.1.1703361768.12801396.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.1714578744.1.1703361344.12651898.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.1714512485.1.1703361630.15672713.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.859333938.1.1703360981.12734014.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.811753780.1.1703361206.12785980.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.859333938.1.1703361295.12743139.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.811753780.1.1703361322.12789664.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.1714578744.1.1703361058.12643263.mp4 0    0.971680    0.952148    0.993164    0.994141     1.000000        0.999023        0.920410        0.994141        0.336914
2  1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621    s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.859333938.1.1703361718.12755143.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.845494328.1.1703361768.18330154.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.1714512485.1.1703361466.15668025.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.811753780.1.1703361481.12794443.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.1714578744.1.1703360962.12640733.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.811753780.1.1703361026.12780970.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.811753780.1.1703361377.12791344.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.859333938.1.1703361420.12747249.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.811753780.1.1703361377.12791344.mp4 0    0.860352    0.920410    0.987793    0.970215     0.999023        0.995117        0.077881        0.457764        0.915039
3  1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786   s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.811753780.1.1703361688.12799561.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.859333938.1.1703361901.12759740.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.1714578744.1.1703361335.12651601.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.1714578744.1.1703361562.12658450.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.1714578744.1.1703360943.12640187.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.845494328.1.1703361161.18312188.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.845494328.1.1703361225.18314150.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.859333938.1.1703361240.12741465.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.845494328.1.1703361225.18314150.mp4 0    0.826172    0.982422    0.993652    0.994629     0.992188        0.759766        0.053925        0.766113        0.307373
4  1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049   s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.859333938.1.1703361941.12760699.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.1714512485.1.1703361859.15678907.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.845494328.1.1703361547.18324416.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.845494328.1.1703361716.18328857.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.845494328.1.1703361087.18309989.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.859333938.1.1703361270.12742427.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.1714578744.1.1703361390.12653302.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.845494328.1.1703361411.18320332.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.1714512485.1.1703361422.15666500.mp4 0    0.954102    0.891602    0.987305    0.591797     1.000000        0.996582        0.785156        0.169922        0.894043

/tmp/ipykernel_28402/3339299357.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(select_views_for_study)

In [53]:
preview.head()

                                        DeidentifiedStudyID                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         CSV_Row  conf_p_a2c  conf_p_a3c  conf_p_a4c  conf_p_a5c  conf_p_plax  conf_p_psax-av  conf_p_psax-mv  conf_p_psax-ap  conf_p_psax-pm
0  1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.1714512485.1.1703361101.15655449.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.1714578744.1.1703361154.12646028.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.1714512485.1.1703360773.15644824.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.1714512485.1.1703361209.15658939.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.845494328.1.1703360348.18286976.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.811753780.1.1703360512.12765587.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.859333938.1.1703360598.12722190.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.859333938.1.1703361288.12742938.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.859333938.1.1703360624.12723048.mp4 0    0.833496    0.985840    0.985840    0.426270     0.999023        0.997070        0.162964        0.978516        0.966309
1  1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.1714512485.1.1703361685.15674252.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.811753780.1.1703361768.12801396.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.1714578744.1.1703361344.12651898.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.1714512485.1.1703361630.15672713.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.859333938.1.1703360981.12734014.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.811753780.1.1703361206.12785980.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.859333938.1.1703361295.12743139.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.811753780.1.1703361322.12789664.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.1714578744.1.1703361058.12643263.mp4 0    0.971680    0.952148    0.993164    0.994141     1.000000        0.999023        0.920410        0.994141        0.336914
2  1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621    s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.859333938.1.1703361718.12755143.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.845494328.1.1703361768.18330154.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.1714512485.1.1703361466.15668025.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.811753780.1.1703361481.12794443.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.1714578744.1.1703360962.12640733.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.811753780.1.1703361026.12780970.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.811753780.1.1703361377.12791344.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.859333938.1.1703361420.12747249.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.811753780.1.1703361377.12791344.mp4 0    0.860352    0.920410    0.987793    0.970215     0.999023        0.995117        0.077881        0.457764        0.915039
3  1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786   s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.811753780.1.1703361688.12799561.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.859333938.1.1703361901.12759740.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.1714578744.1.1703361335.12651601.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.1714578744.1.1703361562.12658450.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.1714578744.1.1703360943.12640187.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.845494328.1.1703361161.18312188.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.845494328.1.1703361225.18314150.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.859333938.1.1703361240.12741465.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.845494328.1.1703361225.18314150.mp4 0    0.826172    0.982422    0.993652    0.994629     0.992188        0.759766        0.053925        0.766113        0.307373
4  1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049   s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.859333938.1.1703361941.12760699.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.1714512485.1.1703361859.15678907.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.845494328.1.1703361547.18324416.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.845494328.1.1703361716.18328857.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.845494328.1.1703361087.18309989.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.859333938.1.1703361270.12742427.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.1714578744.1.1703361390.12653302.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.845494328.1.1703361411.18320332.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.1714512485.1.1703361422.15666500.mp4 0    0.954102    0.891602    0.987305    0.591797     1.000000        0.996582        0.785156        0.169922        0.894043

In [54]:
# ----- split at study level -----
train_val_df, test_df = train_test_split(
    per_study, test_size=0.20, stratify=per_study["label"], random_state=42
)
train_df, val_df = train_test_split(
    train_val_df, test_size=0.20, stratify=train_val_df["label"], random_state=42
)

In [55]:
# ----- save CSVs for VideoGroupDataset -----
# Headered format: columns = canonical view names, plus 'label'
train_df.to_csv(f"csv/multi9_{label_names}_train.csv", index=True, header=True)
val_df.to_csv(f"csv/multi9_{label_names}_val.csv", index=True, header=True)
test_df.to_csv(f"csv/multi9_{label_names}_test.csv", index=True, header=True)

# If your loader expects headerless "paths ... label" per line instead,
# you can also write the prebuilt CSV_Row strings:
# train_hdrless = train_df.apply(lambda r: " ".join([*(r[v] for v in CANONICAL_VIEWS), str(int(r['label']))]), axis=1)
# val_hdrless   = val_df.apply(lambda r: " ".join([*(r[v] for v in CANONICAL_VIEWS), str(int(r['label']))]), axis=1)
# test_hdrless  = test_df.apply(lambda r: " ".join([*(r[v] for v in CANONICAL_VIEWS), str(int(r['label']))]), axis=1)
# train_hdrless.to_csv(f"csv/multi9_{label_names}_train_headerless.csv", index=False, header=False)
# val_hdrless.to_csv(f"csv/multi9_{label_names}_val_headerless.csv", index=False, header=False)
# test_hdrless.to_csv(f"csv/multi9_{label_names}_test_headerless.csv", index=False, header=False)

In [56]:
# prerequisites
MISSING_TOKEN = "MISS"
CANONICAL_VIEWS = [
    "p_a2c","p_a3c","p_a4c","p_a5c","p_plax","p_psax-av","p_psax-mv","p_psax-ap","p_psax-pm"
]
view_cols = [c for c in CANONICAL_VIEWS if c in train_df.columns]

# boolean mask of missing per cell (MISS, empty string, or NaN)
_stripped = train_df[view_cols].astype(str).apply(lambda c: c.str.strip())
missing_mask = (
    train_df[view_cols].isna()
    | _stripped.eq("")            # empty
    | _stripped.eq(MISSING_TOKEN) # explicit missing token
)

# rows with any missing view
rows_with_missing = missing_mask.any(axis=1)
n_missing_rows = int(rows_with_missing.sum())
pct_missing_rows = 100.0 * n_missing_rows / max(1, len(train_df))

print(f"Rows with ≥1 missing view: {n_missing_rows}/{len(train_df)} ({pct_missing_rows:.2f}%)")

# which views are missing per row
missing_views_series = missing_mask.apply(
    lambda r: [v for v, m in zip(view_cols, r.values) if m], axis=1
)

# locate and inspect
missing_rows_df = (
    train_df.loc[rows_with_missing, view_cols + ["label"]]
            .assign(missing_views=missing_views_series[rows_with_missing],
                    n_missing=missing_mask.sum(axis=1)[rows_with_missing])
)

# include study id if it's the index; otherwise adjust the column name accordingly
if train_df.index.name:
    missing_rows_df = missing_rows_df.reset_index().rename(columns={train_df.index.name: "DeidentifiedStudyID"})

Rows with ≥1 missing view: 46/29371 (0.16%)

In [57]:
missing_rows_df.head(10)

                                        DeidentifiedStudyID                                                                                                                                                                                                              p_a2c                                                                                                                                                                                                              p_a3c                                                                                                                                                                                                              p_a4c                                                                                                                                                                                                              p_a5c                                                                                                                                                                                                             p_plax                                                                                                                                                                                                        p_psax-av p_psax-mv                                                                                                                                                                                                        p_psax-ap                                                                                                                                                                                                          p_psax-pm  label                                 missing_views  n_missing
0    1.2.276.0.7230010.3.1.2.895627313.1.1725199064.3260958      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725199064.3260958/1.2.276.0.7230010.3.1.3.895627313.1.1725199064.3260959/1.2.276.0.7230010.3.1.4.842097970.1.1725199115.2763250.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725199064.3260958/1.2.276.0.7230010.3.1.3.895627313.1.1725199064.3260959/1.2.276.0.7230010.3.1.4.842097970.1.1725199115.2763250.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725199064.3260958/1.2.276.0.7230010.3.1.3.895627313.1.1725199064.3260959/1.2.276.0.7230010.3.1.4.842097970.1.1725199115.2763250.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725199064.3260958/1.2.276.0.7230010.3.1.3.895627313.1.1725199064.3260959/1.2.276.0.7230010.3.1.4.895693665.1.1725199152.4295266.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725199064.3260958/1.2.276.0.7230010.3.1.3.895627313.1.1725199064.3260959/1.2.276.0.7230010.3.1.4.895693665.1.1725199152.4295266.mp4    s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725199064.3260958/1.2.276.0.7230010.3.1.3.895627313.1.1725199064.3260959/1.2.276.0.7230010.3.1.4.895627313.1.1725199104.3261091.mp4      MISS   s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725199064.3260958/1.2.276.0.7230010.3.1.3.895627313.1.1725199064.3260959/1.2.276.0.7230010.3.1.4.1714500150.1.1725199128.2233717.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725199064.3260958/1.2.276.0.7230010.3.1.3.895627313.1.1725199064.3260959/1.2.276.0.7230010.3.1.4.895627313.1.1725199104.3261091.mp4      0                                   [p_psax-mv]          1
1    1.2.276.0.7230010.3.1.2.895627313.1.1724265499.1302460       s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1724265499.1302460/1.2.276.0.7230010.3.1.3.895627313.1.1724265499.1302461/1.2.276.0.7230010.3.1.4.929392183.1.1724266086.924284.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1724265499.1302460/1.2.276.0.7230010.3.1.3.895627313.1.1724265499.1302461/1.2.276.0.7230010.3.1.4.1667523124.1.1724265927.797324.mp4       s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1724265499.1302460/1.2.276.0.7230010.3.1.3.895627313.1.1724265499.1302461/1.2.276.0.7230010.3.1.4.929392183.1.1724266086.924284.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1724265499.1302460/1.2.276.0.7230010.3.1.3.895627313.1.1724265499.1302461/1.2.276.0.7230010.3.1.4.1667523124.1.1724265927.797324.mp4       s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1724265499.1302460/1.2.276.0.7230010.3.1.3.895627313.1.1724265499.1302461/1.2.276.0.7230010.3.1.4.929392183.1.1724265972.923870.mp4     s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1724265499.1302460/1.2.276.0.7230010.3.1.3.895627313.1.1724265499.1302461/1.2.276.0.7230010.3.1.4.929392183.1.1724266086.924284.mp4      MISS     s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1724265499.1302460/1.2.276.0.7230010.3.1.3.895627313.1.1724265499.1302461/1.2.276.0.7230010.3.1.4.842097970.1.1724266168.554336.mp4       s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1724265499.1302460/1.2.276.0.7230010.3.1.3.895627313.1.1724265499.1302461/1.2.276.0.7230010.3.1.4.842097970.1.1724266168.554336.mp4      0                                   [p_psax-mv]          1
2     1.2.276.0.7230010.3.1.2.842097970.1.1724223529.426829        s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1724223529.426829/1.2.276.0.7230010.3.1.3.842097970.1.1724223529.426830/1.2.276.0.7230010.3.1.4.1667523124.1.1724223984.672825.mp4         s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1724223529.426829/1.2.276.0.7230010.3.1.3.842097970.1.1724223529.426830/1.2.276.0.7230010.3.1.4.929392183.1.1724224140.798741.mp4        s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1724223529.426829/1.2.276.0.7230010.3.1.3.842097970.1.1724223529.426830/1.2.276.0.7230010.3.1.4.1667523124.1.1724223984.672825.mp4        s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1724223529.426829/1.2.276.0.7230010.3.1.3.842097970.1.1724223529.426830/1.2.276.0.7230010.3.1.4.1667523124.1.1724223984.672825.mp4        s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1724223529.426829/1.2.276.0.7230010.3.1.3.842097970.1.1724223529.426830/1.2.276.0.7230010.3.1.4.895693665.1.1724224265.1307735.mp4       s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1724223529.426829/1.2.276.0.7230010.3.1.3.842097970.1.1724223529.426830/1.2.276.0.7230010.3.1.4.842097970.1.1724224513.429874.mp4      MISS      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1724223529.426829/1.2.276.0.7230010.3.1.3.842097970.1.1724223529.426830/1.2.276.0.7230010.3.1.4.1667523124.1.1724224540.674386.mp4        s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1724223529.426829/1.2.276.0.7230010.3.1.3.842097970.1.1724223529.426830/1.2.276.0.7230010.3.1.4.1667523124.1.1724224540.674386.mp4      0                                   [p_psax-mv]          1
3  1.2.276.0.7230010.3.1.2.1714578744.1.1703762724.17468796  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703762724.17468796/1.2.276.0.7230010.3.1.3.1714578744.1.1703762724.17468797/1.2.276.0.7230010.3.1.4.1714512485.1.1703763262.20965082.mp4  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703762724.17468796/1.2.276.0.7230010.3.1.3.1714578744.1.1703762724.17468797/1.2.276.0.7230010.3.1.4.1714512485.1.1703762982.20960237.mp4  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703762724.17468796/1.2.276.0.7230010.3.1.3.1714578744.1.1703762724.17468797/1.2.276.0.7230010.3.1.4.1714512485.1.1703763262.20965082.mp4  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703762724.17468796/1.2.276.0.7230010.3.1.3.1714578744.1.1703762724.17468797/1.2.276.0.7230010.3.1.4.1714512485.1.1703762982.20960237.mp4  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703762724.17468796/1.2.276.0.7230010.3.1.3.1714578744.1.1703762724.17468797/1.2.276.0.7230010.3.1.4.1714512485.1.1703763187.20963752.mp4                                                                                                                                                                                                             MISS      MISS                                                                                                                                                                                                             MISS  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703762724.17468796/1.2.276.0.7230010.3.1.3.1714578744.1.1703762724.17468797/1.2.276.0.7230010.3.1.4.1714578744.1.1703763206.17476570.mp4      0             [p_psax-av, p_psax-mv, p_psax-ap]          3
4    1.2.276.0.7230010.3.1.2.842097970.1.1725256777.2982301     s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1725256777.2982301/1.2.276.0.7230010.3.1.3.842097970.1.1725256777.2982302/1.2.276.0.7230010.3.1.4.1714500150.1.1725257119.2452019.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1725256777.2982301/1.2.276.0.7230010.3.1.3.842097970.1.1725256777.2982302/1.2.276.0.7230010.3.1.4.895627313.1.1725256895.3479703.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1725256777.2982301/1.2.276.0.7230010.3.1.3.842097970.1.1725256777.2982302/1.2.276.0.7230010.3.1.4.895693665.1.1725256942.4510591.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1725256777.2982301/1.2.276.0.7230010.3.1.3.842097970.1.1725256777.2982302/1.2.276.0.7230010.3.1.4.842097970.1.1725256813.2982424.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1725256777.2982301/1.2.276.0.7230010.3.1.3.842097970.1.1725256777.2982302/1.2.276.0.7230010.3.1.4.895627313.1.1725256895.3479703.mp4    s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1725256777.2982301/1.2.276.0.7230010.3.1.3.842097970.1.1725256777.2982302/1.2.276.0.7230010.3.1.4.895693665.1.1725256953.4510633.mp4      MISS    s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1725256777.2982301/1.2.276.0.7230010.3.1.3.842097970.1.1725256777.2982302/1.2.276.0.7230010.3.1.4.895693665.1.1725256953.4510633.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1725256777.2982301/1.2.276.0.7230010.3.1.3.842097970.1.1725256777.2982302/1.2.276.0.7230010.3.1.4.895693665.1.1725256953.4510633.mp4      0                                   [p_psax-mv]          1
5    1.2.276.0.7230010.3.1.2.929392183.1.1724348630.1165907      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.929392183.1.1724348630.1165907/1.2.276.0.7230010.3.1.3.895693665.1.1724348644.1669764/1.2.276.0.7230010.3.1.4.895627313.1.1724349514.1549370.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.929392183.1.1724348630.1165907/1.2.276.0.7230010.3.1.3.895693665.1.1724348644.1669764/1.2.276.0.7230010.3.1.4.895693665.1.1724348902.1670512.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.929392183.1.1724348630.1165907/1.2.276.0.7230010.3.1.3.895693665.1.1724348644.1669764/1.2.276.0.7230010.3.1.4.895693665.1.1724348644.1669765.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.929392183.1.1724348630.1165907/1.2.276.0.7230010.3.1.3.895693665.1.1724348644.1669764/1.2.276.0.7230010.3.1.4.929392183.1.1724349585.1168620.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.929392183.1.1724348630.1165907/1.2.276.0.7230010.3.1.3.895693665.1.1724348644.1669764/1.2.276.0.7230010.3.1.4.895693665.1.1724349165.1671245.mp4    s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.929392183.1.1724348630.1165907/1.2.276.0.7230010.3.1.3.895693665.1.1724348644.1669764/1.2.276.0.7230010.3.1.4.895693665.1.1724348717.1669987.mp4      MISS                                                                                                                                                                                                             MISS                                                                                                                                                                                                               MISS      0             [p_psax-mv, p_psax-ap, p_psax-pm]          3
6    1.2.276.0.7230010.3.1.2.1667523124.1.1724134889.412562      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1724134889.412562/1.2.276.0.7230010.3.1.3.1667523124.1.1724134889.412563/1.2.276.0.7230010.3.1.4.895693665.1.1724134936.1045424.mp4       s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1724134889.412562/1.2.276.0.7230010.3.1.3.1667523124.1.1724134889.412563/1.2.276.0.7230010.3.1.4.895627313.1.1724134911.915323.mp4       s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1724134889.412562/1.2.276.0.7230010.3.1.3.1667523124.1.1724134889.412563/1.2.276.0.7230010.3.1.4.842097970.1.1724135015.164606.mp4       s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1724134889.412562/1.2.276.0.7230010.3.1.3.1667523124.1.1724134889.412563/1.2.276.0.7230010.3.1.4.842097970.1.1724135015.164606.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1724134889.412562/1.2.276.0.7230010.3.1.3.1667523124.1.1724134889.412563/1.2.276.0.7230010.3.1.4.895693665.1.1724134992.1045573.mp4    s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1724134889.412562/1.2.276.0.7230010.3.1.3.1667523124.1.1724134889.412563/1.2.276.0.7230010.3.1.4.895693665.1.1724134992.1045573.mp4      MISS                                                                                                                                                                                                             MISS      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1724134889.412562/1.2.276.0.7230010.3.1.3.1667523124.1.1724134889.412563/1.2.276.0.7230010.3.1.4.895693665.1.1724135023.1045651.mp4      0                        [p_psax-mv, p_psax-ap]          2
7    1.2.276.0.7230010.3.1.2.895627313.1.1725203137.3275823     s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725203137.3275823/1.2.276.0.7230010.3.1.3.895627313.1.1725203137.3275824/1.2.276.0.7230010.3.1.4.1667523124.1.1725203220.2371328.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725203137.3275823/1.2.276.0.7230010.3.1.3.895627313.1.1725203137.3275824/1.2.276.0.7230010.3.1.4.842097970.1.1725203672.2780079.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725203137.3275823/1.2.276.0.7230010.3.1.3.895627313.1.1725203137.3275824/1.2.276.0.7230010.3.1.4.895627313.1.1725203137.3275825.mp4     s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725203137.3275823/1.2.276.0.7230010.3.1.3.895627313.1.1725203137.3275824/1.2.276.0.7230010.3.1.4.1667523124.1.1725203220.2371328.mp4     s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725203137.3275823/1.2.276.0.7230010.3.1.3.895627313.1.1725203137.3275824/1.2.276.0.7230010.3.1.4.1714500150.1.1725203878.2251253.mp4    s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895627313.1.1725203137.3275823/1.2.276.0.7230010.3.1.3.895627313.1.1725203137.3275824/1.2.276.0.7230010.3.1.4.895627313.1.1725203137.3275825.mp4      MISS                                                                                                                                                                                                             MISS                                                                                                                                                                                                               MISS      1             [p_psax-mv, p_psax-ap, p_psax-pm]          3
8    1.2.276.0.7230010.3.1.2.895693665.1.1725244558.4463680     s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895693665.1.1725244558.4463680/1.2.276.0.7230010.3.1.3.895693665.1.1725244558.4463681/1.2.276.0.7230010.3.1.4.1714500150.1.1725244895.2404791.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895693665.1.1725244558.4463680/1.2.276.0.7230010.3.1.3.895693665.1.1725244558.4463681/1.2.276.0.7230010.3.1.4.895693665.1.1725244702.4464219.mp4     s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895693665.1.1725244558.4463680/1.2.276.0.7230010.3.1.3.895693665.1.1725244558.4463681/1.2.276.0.7230010.3.1.4.1714500150.1.1725244895.2404791.mp4      s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895693665.1.1725244558.4463680/1.2.276.0.7230010.3.1.3.895693665.1.1725244558.4463681/1.2.276.0.7230010.3.1.4.895693665.1.1725244665.4464086.mp4     s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.895693665.1.1725244558.4463680/1.2.276.0.7230010.3.1.3.895693665.1.1725244558.4463681/1.2.276.0.7230010.3.1.4.1714500150.1.1725244895.2404791.mp4                                                                                                                                                                                                             MISS      MISS                                                                                                                                                                                                             MISS                                                                                                                                                                                                               MISS      1  [p_psax-av, p_psax-mv, p_psax-ap, p_psax-pm]          4
9   1.2.276.0.7230010.3.1.2.1667523124.1.1725253498.2559709   s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1725253498.2559709/1.2.276.0.7230010.3.1.3.1667523124.1.1725253498.2559710/1.2.276.0.7230010.3.1.4.1667523124.1.1725253519.2559795.mp4   s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1725253498.2559709/1.2.276.0.7230010.3.1.3.1667523124.1.1725253498.2559710/1.2.276.0.7230010.3.1.4.1714500150.1.1725253802.2439435.mp4    s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1725253498.2559709/1.2.276.0.7230010.3.1.3.1667523124.1.1725253498.2559710/1.2.276.0.7230010.3.1.4.895627313.1.1725254040.3468598.mp4   s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1725253498.2559709/1.2.276.0.7230010.3.1.3.1667523124.1.1725253498.2559710/1.2.276.0.7230010.3.1.4.1714500150.1.1725253828.2439519.mp4    s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1725253498.2559709/1.2.276.0.7230010.3.1.3.1667523124.1.1725253498.2559710/1.2.276.0.7230010.3.1.4.895693665.1.1725254016.4499598.mp4  s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1725253498.2559709/1.2.276.0.7230010.3.1.3.1667523124.1.1725253498.2559710/1.2.276.0.7230010.3.1.4.895693665.1.1725254063.4499778.mp4      MISS  s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1725253498.2559709/1.2.276.0.7230010.3.1.3.1667523124.1.1725253498.2559710/1.2.276.0.7230010.3.1.4.895693665.1.1725254063.4499778.mp4    s3://echodata25/results/echo-study-2/1.2.276.0.7230010.3.1.2.1667523124.1.1725253498.2559709/1.2.276.0.7230010.3.1.3.1667523124.1.1725253498.2559710/1.2.276.0.7230010.3.1.4.895693665.1.1725254063.4499778.mp4      0                                   [p_psax-mv]          1

In [58]:
# per-view missing counts
per_view_missing = missing_mask.sum(axis=0).sort_values(ascending=False)
print("\nMissing count per view:\n", per_view_missing)

Missing count per view:
 p_psax-mv    46
p_psax-ap    20
p_psax-pm    11
p_psax-av     7
p_a3c         1
p_a2c         0
p_plax        0
p_a4c         0
p_a5c         0
dtype: int64

In [59]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

# ----- inputs -----
df = all_rvfx_labels.copy()
label_names = "rvfx_labels"
CANONICAL_VIEWS = [
    "p_a2c", "p_a3c", "p_a4c", "p_a5c", "p_plax",
    "p_psax-av", "p_psax-mv", "p_psax-ap", "p_psax-pm"
]
URI_COL = "URI"
STUDY_COL = "DeidentifiedStudyID"
LABEL_COL = "Value"
MISSING_TOKEN = "MISS"

label_mapping = {"normal": 0, "reduced": 1}
df["label_int"] = df[LABEL_COL].map(label_mapping)
if df["label_int"].isna().any():
    raise ValueError(f"Unmapped labels: {df.loc[df['label_int'].isna(), LABEL_COL].unique().tolist()}")

# If your confidence columns are named exactly like the view (p_*), this works;
# otherwise map view -> confidence column name here.
VIEW_PROB_COL = {v: v for v in CANONICAL_VIEWS}

def select_views_for_study(g: pd.DataFrame) -> pd.Series:
    out_paths, out_confs = {}, {}
    g_valid = g[g[URI_COL].astype(str).str.len() > 0].copy()

    for v in CANONICAL_VIEWS:
        pcol = VIEW_PROB_COL.get(v, None)
        if pcol is None or pcol not in g_valid.columns or g_valid.empty:
            out_paths[v] = MISSING_TOKEN
            out_confs[v] = np.nan
            continue
        # pick the URI with max confidence for this view
        idx = g_valid[pcol].astype(float).idxmax()
        best_p = float(g_valid.loc[idx, pcol])
        best_uri = str(g_valid.loc[idx, URI_COL]) if best_p > 0 else MISSING_TOKEN
        out_paths[v] = best_uri
        out_confs[v] = best_p if best_uri != MISSING_TOKEN else np.nan

    # label by majority vote (mode) over rows in the study
    label_int = int(g["label_int"].mode().iloc[0])

    # Build the headerless row string now (URIs in canonical order + label)
    csv_row = " ".join(out_paths[v] for v in CANONICAL_VIEWS) + f" {label_int}"

    rec = {
        "label": label_int,
        "CSV_Row": csv_row,
        **{f"conf_{v}": out_confs[v] for v in CANONICAL_VIEWS},
    }
    return pd.Series(rec)

# one row per study
per_study = (
    df.groupby(STUDY_COL, sort=False, as_index=True)
      .apply(select_views_for_study)
)

# ----- preview (for sanity check) -----
preview = per_study.reset_index()[[STUDY_COL, "CSV_Row", *[f"conf_{v}" for v in CANONICAL_VIEWS]]]
print(preview.head())

# ----- split at study level (stratified) -----
train_val_df, test_df = train_test_split(
    per_study, test_size=0.20, stratify=per_study["label"], random_state=42
)
train_df, val_df = train_test_split(
    train_val_df, test_size=0.20, stratify=train_val_df["label"], random_state=42
)

# ----- write HEADERLESS files (only paths + label) -----
def to_headerless_lines(df_):
    # each line is the pre-built CSV_Row string
    return df_["CSV_Row"]

to_headerless_lines(train_df).to_csv(f"csv/multi9_{label_names}_train.csv", index=False, header=False)
to_headerless_lines(val_df).to_csv(  f"csv/multi9_{label_names}_val.csv",   index=False, header=False)
to_headerless_lines(test_df).to_csv( f"csv/multi9_{label_names}_test.csv",  index=False, header=False)

/tmp/ipykernel_28402/1778920055.py:59: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(select_views_for_study)

                                        DeidentifiedStudyID                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         CSV_Row  conf_p_a2c  conf_p_a3c  conf_p_a4c  conf_p_a5c  conf_p_plax  conf_p_psax-av  conf_p_psax-mv  conf_p_psax-ap  conf_p_psax-pm
0  1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.1714512485.1.1703361101.15655449.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.1714578744.1.1703361154.12646028.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.1714512485.1.1703360773.15644824.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.1714512485.1.1703361209.15658939.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.845494328.1.1703360348.18286976.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.811753780.1.1703360512.12765587.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.859333938.1.1703360598.12722190.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.859333938.1.1703361288.12742938.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360128.15623239/1.2.276.0.7230010.3.1.3.1714512485.1.1703360152.15624003/1.2.276.0.7230010.3.1.4.859333938.1.1703360624.12723048.mp4 0    0.833496    0.985840    0.985840    0.426270     0.999023        0.997070        0.162964        0.978516        0.966309
1  1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147  s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.1714512485.1.1703361685.15674252.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.811753780.1.1703361768.12801396.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.1714578744.1.1703361344.12651898.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.1714512485.1.1703361630.15672713.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.859333938.1.1703360981.12734014.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.811753780.1.1703361206.12785980.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.859333938.1.1703361295.12743139.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.811753780.1.1703361322.12789664.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360841.15647147/1.2.276.0.7230010.3.1.3.1714512485.1.1703360863.15647814/1.2.276.0.7230010.3.1.4.1714578744.1.1703361058.12643263.mp4 0    0.971680    0.952148    0.993164    0.994141     1.000000        0.999023        0.920410        0.994141        0.336914
2  1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621    s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.859333938.1.1703361718.12755143.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.845494328.1.1703361768.18330154.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.1714512485.1.1703361466.15668025.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.811753780.1.1703361481.12794443.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.1714578744.1.1703360962.12640733.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.811753780.1.1703361026.12780970.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.811753780.1.1703361377.12791344.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.859333938.1.1703361420.12747249.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360857.15647621/1.2.276.0.7230010.3.1.3.1714512485.1.1703360881.15648365/1.2.276.0.7230010.3.1.4.811753780.1.1703361377.12791344.mp4 0    0.860352    0.920410    0.987793    0.970215     0.999023        0.995117        0.077881        0.457764        0.915039
3  1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786   s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.811753780.1.1703361688.12799561.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.859333938.1.1703361901.12759740.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.1714578744.1.1703361335.12651601.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.1714578744.1.1703361562.12658450.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.1714578744.1.1703360943.12640187.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.845494328.1.1703361161.18312188.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.845494328.1.1703361225.18314150.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.859333938.1.1703361240.12741465.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360831.15646786/1.2.276.0.7230010.3.1.3.1714578744.1.1703360844.12637352/1.2.276.0.7230010.3.1.4.845494328.1.1703361225.18314150.mp4 0    0.826172    0.982422    0.993652    0.994629     0.992188        0.759766        0.053925        0.766113        0.307373
4  1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049   s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.859333938.1.1703361941.12760699.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.1714512485.1.1703361859.15678907.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.845494328.1.1703361547.18324416.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.845494328.1.1703361716.18328857.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.845494328.1.1703361087.18309989.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.859333938.1.1703361270.12742427.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.1714578744.1.1703361390.12653302.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.845494328.1.1703361411.18320332.mp4 s3://echodata25/results/echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703360870.15648049/1.2.276.0.7230010.3.1.3.1714512485.1.1703360875.15648177/1.2.276.0.7230010.3.1.4.1714512485.1.1703361422.15666500.mp4 0    0.954102    0.891602    0.987305    0.591797     1.000000        0.996582        0.785156        0.169922        0.894043

In [65]:
import numpy as np

N_VIEWS = 9
MISS = "MISS"

def enforce_at_least_one_miss_headerless(df, n_views=N_VIEWS, miss_token=MISS, seed=123):
    """Ensure each CSV_Row has at least one MISS among the n_views paths."""
    rng = np.random.default_rng(seed)
    df = df.copy()

    new_rows = []
    for s in df["CSV_Row"].astype(str).tolist():
        parts = s.strip().split()
        if len(parts) < n_views + 1:
            raise ValueError(f"CSV_Row has {len(parts)} fields; expected {n_views}+label: {s[:200]}")

        paths = parts[:n_views]
        label = parts[-1]

        if all(p != miss_token for p in paths):
            j = int(rng.integers(0, n_views))
            paths[j] = miss_token

        new_rows.append(" ".join(paths + [label]))

    df["CSV_Row"] = new_rows
    return df

train_df_miss = enforce_at_least_one_miss_headerless(train_df, n_views=N_VIEWS)
val_df_miss   = enforce_at_least_one_miss_headerless(val_df,   n_views=N_VIEWS)
test_df_miss  = enforce_at_least_one_miss_headerless(test_df,  n_views=N_VIEWS)

# write headerless (paths + label) with MISS_ prefix
train_df_miss["CSV_Row"].to_csv(f"csv/MISS_multi9_{label_names}_train.csv", index=False, header=False)
val_df_miss["CSV_Row"].to_csv(  f"csv/MISS_multi9_{label_names}_val.csv",   index=False, header=False)
test_df_miss["CSV_Row"].to_csv( f"csv/MISS_multi9_{label_names}_test.csv",  index=False, header=False)

# Multi CSV (Fixed)

In [24]:
import pandas as pd
from sklearn.model_selection import train_test_split

# --- config -------------------------------------------------------------------
# label_names = "mv_function_a4c"        # <-- set your base filename
N = 8                                   # number of URIs per study to emit
test_size = 0.20
val_size_within_trainval = 0.20
RNG = 42

# --- load & label map ---------------------------------------------------------
df = all_rvfx_labels
# df = pd.read_csv(f"csv/{label_names}.csv")

label_mapping = {
    "normal": 0,
    "reduced": 1,
}

df["Value_numeric"] = df["Value"].map(label_mapping)

# sanity
if df["Value_numeric"].isna().any():
    bad = df.loc[df["Value_numeric"].isna(), "Value"].unique().tolist()
    raise ValueError(f"Unmapped labels present: {bad}")

# --- collapse rows to one row per DeidentifiedStudyID with N paths ------------
def rows_for_study(g: pd.DataFrame, n: int) -> pd.Series:
    # keep original order as in the CSV
    uris = g["URI"].tolist()
    if len(uris) == 0:
        # should not happen, but guard anyway
        uris = [""] * n
    elif len(uris) < n:
        uris = uris + [uris[-1]] * (n - len(uris))  # duplicate last until N
    else:
        uris = uris[:n]

    # label: take the mode; if tie, .mode() returns sorted values -> take first
    label_mode = g["Value_numeric"].mode()
    label = int(label_mode.iloc[0])

    out = {f"path{i+1}": uris[i] for i in range(n)}
    out["label"] = label
    return pd.Series(out)

In [25]:
# groupby preserves intra-group row order by default
study_df = (
    df.groupby("DeidentifiedStudyID", sort=False)
      .apply(rows_for_study, n=N)
      .reset_index(drop=True)
)

# --- split at the STUDY level (to avoid leakage) ------------------------------
train_val_df, test_df = train_test_split(
    study_df,
    test_size=test_size,
    stratify=study_df["label"],
    random_state=RNG,
)

train_df, val_df = train_test_split(
    train_val_df,
    test_size=val_size_within_trainval,
    stratify=train_val_df["label"],
    random_state=RNG,
)

# --- stats --------------------------------------------------------------------
def pct(n, d): return 100.0 * n / max(1, d)

print(f"Total studies: {len(study_df)}")
print(f"Train: {len(train_df)} ({pct(len(train_df), len(study_df)):.1f}%)")
print(f"Val:   {len(val_df)} ({pct(len(val_df), len(study_df)):.1f}%)")
print(f"Test:  {len(test_df)} ({pct(len(test_df), len(study_df)):.1f}%)")

Total studies: 45893
Train: 29371 (64.0%)
Val:   7343 (16.0%)
Test:  9179 (20.0%)

/tmp/ipykernel_28402/2997230528.py:4: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(rows_for_study, n=N)

In [30]:
import os 

print("\nLabel distribution (studies):")
for name, part in [("Train", train_df), ("Val", val_df), ("Test", test_df)]:
    counts = part["label"].value_counts().sort_index()
    print(name + ": " + ", ".join(f"{k}={v}" for k, v in counts.items()))

# --- write CSVs and print absolute file paths ---------------------------------
cols = [f"path{i+1}" for i in range(N)] + ["label"]
written_paths = []
for name, part in [("train", train_df), ("val", val_df), ("test", test_df)]:
    out_path = f"csv/{label_names}_{name}_N{N}.csv"
    part[cols].to_csv(out_path, header=False, index=False, sep=" ")
    abs_path = os.path.abspath(out_path)
    written_paths.append(abs_path)
    print(f"Wrote {abs_path}  ({len(part)} rows)")

# --- (optional) also keep the original V-JEPA 2 'URI label' files -------------
# If you still want per-clip rows, uncomment below.

# for name, part in [("train", train_df), ("val", val_df), ("test", test_df)]:
#     long_rows = []
#     for _, r in part.iterrows():
#         paths = [r[f"path{i+1}"] for i in range(N)]
#         for p in paths:
#             long_rows.append((p, r["label"]))
#     long_df = pd.DataFrame(long_rows, columns=["URI", "Value_numeric"])
#     long_df.to_csv(f"{label_names}_{name}_full.csv", header=False, index=False, sep=" ")

Label distribution (studies):
Train: 0=25003, 1=4368
Val: 0=6251, 1=1092
Test: 0=7814, 1=1365
Wrote /mnt/custom-file-systems/efs/fs-0049217cdf69186d7_fsap-0fa7145b64eaa046b/vjepa2/data/csv/multi_rvfx_labels_train_N8.csv  (29371 rows)
Wrote /mnt/custom-file-systems/efs/fs-0049217cdf69186d7_fsap-0fa7145b64eaa046b/vjepa2/data/csv/multi_rvfx_labels_val_N8.csv  (7343 rows)
Wrote /mnt/custom-file-systems/efs/fs-0049217cdf69186d7_fsap-0fa7145b64eaa046b/vjepa2/data/csv/multi_rvfx_labels_test_N8.csv  (9179 rows)

In [32]:
train_df.head()

,path1,path2,path3,path4,path5,path6,path7,path8,label
9329,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,0
9169,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,0
36108,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,0
40466,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,0
12983,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,s3://echodata25/results/echo-study-2/1.2.276.0...,0

# Old

In [6]:
label_names = 'a4c_rvfx_labels'
a4c_rvfx_labels.to_csv(f"{label_names}.csv")

In [7]:
a4c_rvfx_labels.head()

,DeidentifiedStudyID,URI,Value
0,1.2.276.0.7230010.3.1.2.1714512485.1.170336012...,s3://echodata25/results/echo-study/1.2.276.0.7...,normal
1,1.2.276.0.7230010.3.1.2.1714512485.1.170336084...,s3://echodata25/results/echo-study/1.2.276.0.7...,normal
2,1.2.276.0.7230010.3.1.2.1714512485.1.170336083...,s3://echodata25/results/echo-study/1.2.276.0.7...,normal
3,1.2.276.0.7230010.3.1.2.1714512485.1.170336445...,s3://echodata25/results/echo-study/1.2.276.0.7...,normal
4,1.2.276.0.7230010.3.1.2.1714512485.1.170336445...,s3://echodata25/results/echo-study/1.2.276.0.7...,normal

In [8]:
a4c_rvfx_labels['Value'].value_counts()

Value
normal     415700
reduced     78917
Name: count, dtype: int64

In [9]:
import pandas as pd  
from sklearn.model_selection import train_test_split  
  
# Read mitral valve regurgitation labels for A4C videos
df = pd.read_csv(f"{label_names}.csv")  
  
# Create label mapping for severity levels  
label_mapping = {  
    'normal': 0,  
    'reduced': 1
}  

def build_train_test(df, label_mapping):  
    # Convert string labels to integers  
    df['Value_numeric'] = df['Value'].map(label_mapping)  
      
    # Verify all labels were mapped correctly  
    if df['Value_numeric'].isna().any():  
        print("Warning: Some labels couldn't be mapped!")  
        print("Unmapped labels:", df[df['Value_numeric'].isna()]['Value'].unique())  
      
    # First split: separate out test set (60% train+val, 40% test)  
    train_val_df, test_df = train_test_split(  
        df,   
        test_size=0.2,  # 20% for test  
        stratify=df['Value_numeric'],   
        random_state=42  
    )  
      
    # Second split: split train+val into train and validation (64% train, 16% val, 20% test)  
    train_df, val_df = train_test_split(  
        train_val_df,  
        test_size=0.2,  # 20% of remaining 80% = 16% of total  
        stratify=train_val_df['Value_numeric'],  
        random_state=42  
    )  

    return train_df, val_df, test_df

In [10]:
train_df, val_df, test_df = build_train_test(df, label_mapping)

# Save files with URI and numeric labels (as expected by V-JEPA 2)  
train_df[['URI', 'Value_numeric']].to_csv(f"{label_names}_train.csv", header=False, index=False, sep=' ')  
val_df[['URI', 'Value_numeric']].to_csv(f"{label_names}_val.csv", header=False, index=False, sep=' ')  
test_df[['URI', 'Value_numeric']].to_csv(f"{label_names}_test.csv", header=False, index=False, sep=' ')  
  
# Print split statistics  
print(f"Total samples: {len(df)}")  
print(f"Train: {len(train_df)} ({len(train_df)/len(df)*100:.1f}%)")  
print(f"Validation: {len(val_df)} ({len(val_df)/len(df)*100:.1f}%)")  
print(f"Test: {len(test_df)} ({len(test_df)/len(df)*100:.1f}%)")  
  
# Print label distribution for each split  
print("\nLabel distribution:")  
for split_name, split_df in [("Train", train_df), ("Val", val_df), ("Test", test_df)]:  
    print(f"{split_name}:")  
    for label, count in split_df['Value_numeric'].value_counts().sort_index().items():  
        original_label = [k for k, v in label_mapping.items() if v == label][0]  
        print(f"  {label} ({original_label}): {count}")

Total samples: 494617
Train: 316554 (64.0%)
Validation: 79139 (16.0%)
Test: 98924 (20.0%)

Label distribution:
Train:
  0 (normal): 266047
  1 (reduced): 50507
Val:
  0 (normal): 66512
  1 (reduced): 12627
Test:
  0 (normal): 83141
  1 (reduced): 15783

# Make a Full Subset

In [11]:
# --- save in V-JEPA 2 format ----------------------------------------
for name, df_small in [("train", train_df),
                       ("val",   val_df),
                       ("test",  test_df)]:
    df_small[["URI", "Value_numeric"]].to_csv(
        f"{label_names}_{name}_full.csv",
        header=False, index=False, sep=" "
    )

# Make a Tiny Subset

In [19]:
import numpy as np
import pandas as pd

def sample_per_class(df: pd.DataFrame,
                     label_col: str = "Value_numeric",
                     n_per_class: int = 500,
                     seed: int = 0) -> pd.DataFrame:
    """Balanced down-sample for fast overfit/debug runs."""
    rng = np.random.default_rng(seed)
    return (
        df.groupby(label_col, group_keys=False)
          .apply(lambda g: g.sample(min(len(g), n_per_class), random_state=rng.integers(1e9)))
          .reset_index(drop=True)
    )

# --- choose sizes ----------------------------------------------------
train_small = sample_per_class(train_df, n_per_class=1000)   # 2 000 rows (1 000 × 2 classes)
val_small   = sample_per_class(val_df,   n_per_class=250)    #   500 rows
test_small  = sample_per_class(test_df,  n_per_class=250)    #   500 rows

# --- save in V-JEPA 2 format ----------------------------------------
for name, df_small in [("train", train_small),
                       ("val",   val_small),
                       ("test",  test_small)]:
    df_small[["URI", "Value_numeric"]].to_csv(
        f"{label_names}_{name}_tiny.csv",
        header=False, index=False, sep=" "
    )

# quick sanity check
for split, d in [("train", train_small), ("val", val_small), ("test", test_small)]:
    counts = d["Value_numeric"].value_counts().sort_index().to_dict()
    print(split, len(d), counts)

train 2000 {0: 1000, 1: 1000}
val 500 {0: 250, 1: 250}
test 500 {0: 250, 1: 250}

/tmp/ipykernel_3991/388687322.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.sample(min(len(g), n_per_class), random_state=rng.integers(1e9)))
/tmp/ipykernel_3991/388687322.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.sample(min(len(g), n_per_class), random_state=rng.integers(1e9)))
/tmp/ipykernel_3991/388687322.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: g.sample(min(len(g), n_per_class), random_state=rng.integers(1e9)))