In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

import os

In [2]:
data_dir = '/cluster/projects/bwanggroup/echo_reports/echo-reports/data/dataset/Lee_Echo_Syngo'
adler = pd.read_csv(os.path.join(data_dir, 'Adler.csv'))
analytics_report = pd.read_csv(os.path.join(data_dir, 'Analytics_Report.csv'))
analytics_study = pd.read_csv(os.path.join(data_dir, 'AnalyticsStudy.csv'))
department = pd.read_csv(os.path.join(data_dir, 'Department.csv'))
field_map = pd.read_csv(os.path.join(data_dir, 'FieldMap.csv'))
measurement_type = pd.read_csv(os.path.join(data_dir, 'MeasurementType.csv'))
modalities = pd.read_csv(os.path.join(data_dir, 'Modalities.csv'))
observations = pd.read_csv(os.path.join(data_dir, 'Observations.csv'))
study_details = pd.read_csv(os.path.join(data_dir, 'StudyDetails.csv'))

/tmp/ipykernel_1433511/3515026001.py:3: DtypeWarning: Columns (18,19,23,24,36,37) have mixed types. Specify dtype option on import or set low_memory=False.
  analytics_report = pd.read_csv(os.path.join(data_dir, 'Analytics_Report.csv'))
/tmp/ipykernel_1433511/3515026001.py:10: DtypeWarning: Columns (6,7,8,16) have mixed types. Specify dtype option on import or set low_memory=False.
  study_details = pd.read_csv(os.path.join(data_dir, 'StudyDetails.csv'))

In [3]:
aws_uhn = pd.read_csv('/cluster/projects/bwanggroup/alif/home_projects_v2/aws/aws_uhn.csv', index_col=0)
print(aws_uhn.shape)

(320854, 9)

In [4]:
len(observations)

6577032

In [5]:
observations.head()

   StudyRef  ObservationID   Value    Type                         Name
0   1000750              9      _2   OTHER      EF_4CH_out_of_range_obs
1   1000750             10      _2   OTHER  EF_Biplane_out_of_range_obs
2   1000750             11  normal  NORMAL             LV_EF_2D-ASE_obs
3   1000750             12      _2   OTHER       EF_2D_out_of_range_obs
4   1000750             13  normal  NORMAL             LV_FS_2D-ASE_obs

# HeartLab

In [6]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

import os

In [7]:
data_dir = '/cluster/projects/bwanggroup/echo_reports/echo-reports/data/dataset'

msmt_defs = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_DEFINITIONS.csv'))
msmt_formula = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_FORMULA.csv'))
msmt_groups = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_GROUPS.csv'))
msmt_intersects = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_INTERSECTS.csv'))
msmt_lists = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_LISTS.csv'))
msmt = pd.read_csv(os.path.join(data_dir,'MEASUREMENTS.csv'))

findings = pd.read_csv(os.path.join(data_dir,'ENCOADMIN_FINDINGS.csv'))
finding_groups = pd.read_csv(os.path.join(data_dir,'ENCOADMIN_FINDING_GROUPS.csv'))
finding_intersects = pd.read_csv(os.path.join(data_dir,'ENCOADMIN_FINDING_INTERSECTS.csv'))

patients = pd.read_csv(os.path.join(data_dir,'Patients_No_PHI.csv'))
reports = pd.read_csv(os.path.join(data_dir,'REPORTS.csv'))
series = pd.read_csv(os.path.join(data_dir,'SERIES.csv'))
studies = pd.read_csv(os.path.join(data_dir,'STUDIES.csv'))

/tmp/ipykernel_1433511/92640382.py:6: DtypeWarning: Columns (7,10,11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  msmt_intersects = pd.read_csv(os.path.join(data_dir,'MEASUREMENT_INTERSECTS.csv'))
/tmp/ipykernel_1433511/92640382.py:15: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  reports = pd.read_csv(os.path.join(data_dir,'REPORTS.csv'))
/tmp/ipykernel_1433511/92640382.py:16: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  series = pd.read_csv(os.path.join(data_dir,'SERIES.csv'))
/tmp/ipykernel_1433511/92640382.py:17: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  studies = pd.read_csv(os.path.join(data_dir,'STUDIES.csv'))

In [9]:
hl_link = pd.read_csv('../heartlab_rep_study_video.csv')

In [10]:
print(len(hl_link))
hl_link.head()

196447

,OriginalStudyID,OriginalPatientID,DeidentifiedStudyID,DeidentifiedPatientID,SERI_ID,STUDY_ID,REP_ID,STUDY_INSTANCE_UID
0,1.2.124.113532.36.59504.16340.20101008.134646.290320,2566463,1.2.276.0.7230010.3.1.2.845494328.1.1703190346.14552982,847aa94b-235e-4b95-a8cd-098b14f5ed38,501919,256599,242059.0,1.2.124.113532.36.59504.16340.20101008.134646.290320
1,1.2.840.113619.2.185.2551.1239109659.0.3,3778399,1.2.276.0.7230010.3.1.2.859333938.1.1703353467.12454807,b5710e8c-fb6b-43b3-ae08-5ad07ef48376,383739,195252,192302.0,1.2.840.113619.2.185.2551.1239109659.0.3
2,1.3.12.2.1107.5.5.10.400111.30000013031207394725000000003,2084574,1.2.276.0.7230010.3.1.2.1714578744.1.1703743505.17198835,a0be47f9-fc3b-43a3-b22a-672a4426a904,715332,347756,311704.0,1.3.12.2.1107.5.5.10.400111.30000013031207394725000000003
3,1.2.840.113619.2.98.4671.1159859574.0.1268,2976665,1.2.276.0.7230010.3.1.2.859333938.1.1703375216.12991674,7c5babb0-3fc0-4b26-ba88-61b336fbc5f2,221150,102508,106628.0,1.2.840.113619.2.98.4671.1159859574.0.1268
4,1.2.840.113663.1500.1.323664363.1.1.20100118.130024.875,2351919,1.2.276.0.7230010.3.1.2.1714578744.1.1703514185.14878754,330bc9c9-50ed-43bc-a9f6-3daf2778ba24,439233,226079,217227.0,1.2.840.113663.1500.1.323664363.1.1.20100118.130024.875

In [11]:
aws_heartlab = pd.read_csv('/cluster/projects/bwanggroup/alif/home_projects_v2/aws/aws_heartlab_0806.csv', index_col=0)
print(aws_heartlab.shape)

(215113, 12)

In [12]:
finding_intersects = finding_intersects.merge(
    findings[['ID', 'HLCODE']], 
    left_on='FIN_ID', 
    right_on='ID', 
    how='left'
).drop(columns='ID_y').rename(columns={'ID_x': 'ID'})

# Mitral Valve

In [13]:
# Filter for rows containing 'pacemaker' in HLCODE
hl_mvr = finding_intersects[finding_intersects['HLCODE'].str.contains('mitral valve', case=False, na=False)]

In [14]:
hl_mvr.head()

,ID,FIN_ID,PHAS_ID,NOTE,SEQA_ID,SEQB_ID,SEQC_ID,REP_ID,SEQD_ID,STRUCTURE_GROUP_SEQ,HLCODE
1,6226,364,1,Regurgitant orifice area by PISA method is 0.44 cmsq.,NaN,NaN,NaN,2028,NaN,NaN,mitral valve^function^regurgitation^severe
8,4009033,316,1,NaN,NaN,NaN,NaN,185500,NaN,NaN,mitral valve^structure^morphology^normal
9,4009034,359,1,NaN,NaN,NaN,NaN,185500,NaN,NaN,mitral valve^function^regurgitation^mild
26,6253,422,1,NaN,NaN,NaN,NaN,2033,NaN,NaN,mitral valve^general^general^normal
52,4010186,358,1,NaN,NaN,NaN,NaN,185565,NaN,NaN,local^mitral valve^function^regurgitation^trivial^358

In [15]:
codes = finding_intersects['HLCODE'].str.strip().str.lower()
hl_mvr = finding_intersects[codes.str.contains('mitral valve.*regurgitation', na=False)]
print(len(hl_mvr))
hl_mvr.head()

250592

,ID,FIN_ID,PHAS_ID,NOTE,SEQA_ID,SEQB_ID,SEQC_ID,REP_ID,SEQD_ID,STRUCTURE_GROUP_SEQ,HLCODE
1,6226,364,1,Regurgitant orifice area by PISA method is 0.44 cmsq.,NaN,NaN,NaN,2028,NaN,NaN,mitral valve^function^regurgitation^severe
9,4009034,359,1,NaN,NaN,NaN,NaN,185500,NaN,NaN,mitral valve^function^regurgitation^mild
52,4010186,358,1,NaN,NaN,NaN,NaN,185565,NaN,NaN,local^mitral valve^function^regurgitation^trivial^358
76,4012732,359,1,NaN,NaN,NaN,NaN,185702,NaN,NaN,mitral valve^function^regurgitation^mild
87,4229,358,1,"There is mitral annuloplasty ring visualized. Peak/mean gradient of 6/2 mmHg, valve area of 2.5 cmsq.",NaN,NaN,NaN,1853,NaN,NaN,local^mitral valve^function^regurgitation^trivial^358

In [16]:
keep = [
    'local^mitral valve^function^regurgitation^trivial^358',
    'mitral valve^function^regurgitation^mild',
    'mitral valve^function^regurgitation^mild to moderate',
    'mitral valve^function^regurgitation^no evidence of',
    'mitral valve^function^regurgitation^moderate',
    'mitral valve^function^regurgitation^severe',
    'mitral valve^function^regurgitation^moderate to severe'
]

hl_mvr_sel = hl_mvr[hl_mvr['HLCODE'].isin(keep)].copy()

In [79]:
mapping_two = {
    'mitral valve^function^regurgitation^no evidence of': 'trivial',
    'local^mitral valve^function^regurgitation^trivial^358': 'trivial',
    'mitral valve^function^regurgitation^mild': 'trivial',
    'mitral valve^function^regurgitation^mild to moderate': 'moderate_or_greater',
    'mitral valve^function^regurgitation^moderate': 'moderate_or_greater',
    'mitral valve^function^regurgitation^moderate to severe': 'moderate_or_greater',
    'mitral valve^function^regurgitation^severe': 'moderate_or_greater'
}

hl_mvr_sel['Regurgitation_Binary'] = hl_mvr_sel['HLCODE'].map(mapping_two)

In [80]:
print(hl_mvr_sel['Regurgitation_Binary'].dropna().value_counts())

Regurgitation_Binary
trivial                215966
moderate_or_greater     34120
Name: count, dtype: int64

In [89]:
# REP_IDs that appear in the pacemaker dataframe
hl_mvr_ids = hl_mvr_sel['REP_ID'].dropna().unique()
print(len(hl_mvr_ids))

# Split hl_link into pacemaker / no-pacemaker subsets
hl_mvr_labels = hl_link[hl_link['REP_ID'].isin(hl_mvr_ids)].copy()

250025

In [90]:
hl_mvr_labels_final = hl_mvr_sel.merge(
    hl_mvr_labels,
    on='REP_ID',
    how='inner',
    suffixes=('', '_drop')  # keep REP_ID as-is, add suffix to duplicates
)

# Remove the duplicate REP_ID column if created
if 'REP_ID_drop' in hl_mvr_labels_final.columns:
    hl_mvr_labels_final = hl_mvr_labels_final.drop(columns=['REP_ID_drop'])

print(hl_mvr_labels_final.columns)
print(hl_mvr_labels_final.shape)
display(hl_mvr_labels_final.head())

Index(['ID', 'FIN_ID', 'PHAS_ID', 'NOTE', 'SEQA_ID', 'SEQB_ID', 'SEQC_ID',
       'REP_ID', 'SEQD_ID', 'STRUCTURE_GROUP_SEQ', 'HLCODE',
       'Regurgitation_Binary', 'OriginalStudyID', 'OriginalPatientID',
       'DeidentifiedStudyID', 'DeidentifiedPatientID', 'SERI_ID', 'STUDY_ID',
       'STUDY_INSTANCE_UID'],
      dtype='object')
(170964, 19)

,ID,FIN_ID,PHAS_ID,NOTE,SEQA_ID,SEQB_ID,SEQC_ID,REP_ID,SEQD_ID,STRUCTURE_GROUP_SEQ,HLCODE,Regurgitation_Binary,OriginalStudyID,OriginalPatientID,DeidentifiedStudyID,DeidentifiedPatientID,SERI_ID,STUDY_ID,STUDY_INSTANCE_UID
0,4009034,359,1,NaN,NaN,NaN,NaN,185500,NaN,NaN,mitral valve^function^regurgitation^mild,trivial,1.2.124.113532.6.23355.16818.20090127.101618.4783525,2126381,1.2.276.0.7230010.3.1.2.1714578744.1.1703275050.10646188,ae6154bc-d23e-41d0-a5e3-141d81870b6d,370189,186986,1.2.124.113532.6.23355.16818.20090127.101618.4783525
1,4010186,358,1,NaN,NaN,NaN,NaN,185565,NaN,NaN,local^mitral valve^function^regurgitation^trivial^358,trivial,1.2.840.113619.2.185.2475.1233062503.0.21,3291779,1.2.276.0.7230010.3.1.2.1714512485.1.1703347766.15036398,31630669-811d-4ea0-ab56-30e7c1bb350d,370307,187061,1.2.840.113619.2.185.2475.1233062503.0.21
2,4012732,359,1,NaN,NaN,NaN,NaN,185702,NaN,NaN,mitral valve^function^regurgitation^mild,trivial,1.2.840.113619.2.185.2475.1233148768.0.2,2807686,1.2.276.0.7230010.3.1.2.1714578744.1.1703347787.12098204,d9ffaae8-0c7c-4662-a007-e6be89f86040,370577,187228,1.2.840.113619.2.185.2475.1233148768.0.2
3,4012756,358,1,NaN,NaN,NaN,NaN,185703,NaN,NaN,local^mitral valve^function^regurgitation^trivial^358,trivial,1.2.840.113619.2.185.2475.1233150619.0.2,1120926,1.2.276.0.7230010.3.1.2.859333938.1.1703347783.12184958,df01c3d2-1684-4951-ae6d-30b82cca719b,370578,187229,1.2.840.113619.2.185.2475.1233150619.0.2
4,4014422,359,1,NaN,NaN,NaN,NaN,185817,NaN,NaN,mitral valve^function^regurgitation^mild,trivial,1.2.840.113663.1500.1.242451848.1.1.20090129.145057.453,2892996,1.2.276.0.7230010.3.1.2.1714512485.1.1703426550.17045351,13f52f05-e9e5-4c0d-b18a-b84312166b06,370806,187370,1.2.840.113663.1500.1.242451848.1.1.20090129.145057.453

In [94]:
hl_mvr_labels_final = hl_mvr_labels_final.merge(
    aws_heartlab[['OriginalStudyID', 's3_key']],  # only needed columns
    on='OriginalStudyID',
    how='left'
)

print(hl_mvr_labels_final.shape)
display(hl_mvr_labels_final.head())

(170966, 20)

,ID,FIN_ID,PHAS_ID,NOTE,SEQA_ID,SEQB_ID,SEQC_ID,REP_ID,SEQD_ID,STRUCTURE_GROUP_SEQ,HLCODE,Regurgitation_Binary,OriginalStudyID,OriginalPatientID,DeidentifiedStudyID,DeidentifiedPatientID,SERI_ID,STUDY_ID,STUDY_INSTANCE_UID,s3_key
0,4009034,359,1,NaN,NaN,NaN,NaN,185500,NaN,NaN,mitral valve^function^regurgitation^mild,trivial,1.2.124.113532.6.23355.16818.20090127.101618.4783525,2126381,1.2.276.0.7230010.3.1.2.1714578744.1.1703275050.10646188,ae6154bc-d23e-41d0-a5e3-141d81870b6d,370189,186986,1.2.124.113532.6.23355.16818.20090127.101618.4783525,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703275050.10646188/
1,4010186,358,1,NaN,NaN,NaN,NaN,185565,NaN,NaN,local^mitral valve^function^regurgitation^trivial^358,trivial,1.2.840.113619.2.185.2475.1233062503.0.21,3291779,1.2.276.0.7230010.3.1.2.1714512485.1.1703347766.15036398,31630669-811d-4ea0-ab56-30e7c1bb350d,370307,187061,1.2.840.113619.2.185.2475.1233062503.0.21,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703347766.15036398/
2,4012732,359,1,NaN,NaN,NaN,NaN,185702,NaN,NaN,mitral valve^function^regurgitation^mild,trivial,1.2.840.113619.2.185.2475.1233148768.0.2,2807686,1.2.276.0.7230010.3.1.2.1714578744.1.1703347787.12098204,d9ffaae8-0c7c-4662-a007-e6be89f86040,370577,187228,1.2.840.113619.2.185.2475.1233148768.0.2,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703347787.12098204/
3,4012756,358,1,NaN,NaN,NaN,NaN,185703,NaN,NaN,local^mitral valve^function^regurgitation^trivial^358,trivial,1.2.840.113619.2.185.2475.1233150619.0.2,1120926,1.2.276.0.7230010.3.1.2.859333938.1.1703347783.12184958,df01c3d2-1684-4951-ae6d-30b82cca719b,370578,187229,1.2.840.113619.2.185.2475.1233150619.0.2,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703347783.12184958/
4,4014422,359,1,NaN,NaN,NaN,NaN,185817,NaN,NaN,mitral valve^function^regurgitation^mild,trivial,1.2.840.113663.1500.1.242451848.1.1.20090129.145057.453,2892996,1.2.276.0.7230010.3.1.2.1714512485.1.1703426550.17045351,13f52f05-e9e5-4c0d-b18a-b84312166b06,370806,187370,1.2.840.113663.1500.1.242451848.1.1.20090129.145057.453,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703426550.17045351/

In [96]:
hl_mvr_labels_final = hl_mvr_labels_final.dropna(subset=['s3_key'])

print(hl_mvr_labels_final.shape)
display(hl_mvr_labels_final.head())

(170966, 20)

,ID,FIN_ID,PHAS_ID,NOTE,SEQA_ID,SEQB_ID,SEQC_ID,REP_ID,SEQD_ID,STRUCTURE_GROUP_SEQ,HLCODE,Regurgitation_Binary,OriginalStudyID,OriginalPatientID,DeidentifiedStudyID,DeidentifiedPatientID,SERI_ID,STUDY_ID,STUDY_INSTANCE_UID,s3_key
0,4009034,359,1,NaN,NaN,NaN,NaN,185500,NaN,NaN,mitral valve^function^regurgitation^mild,trivial,1.2.124.113532.6.23355.16818.20090127.101618.4783525,2126381,1.2.276.0.7230010.3.1.2.1714578744.1.1703275050.10646188,ae6154bc-d23e-41d0-a5e3-141d81870b6d,370189,186986,1.2.124.113532.6.23355.16818.20090127.101618.4783525,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703275050.10646188/
1,4010186,358,1,NaN,NaN,NaN,NaN,185565,NaN,NaN,local^mitral valve^function^regurgitation^trivial^358,trivial,1.2.840.113619.2.185.2475.1233062503.0.21,3291779,1.2.276.0.7230010.3.1.2.1714512485.1.1703347766.15036398,31630669-811d-4ea0-ab56-30e7c1bb350d,370307,187061,1.2.840.113619.2.185.2475.1233062503.0.21,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703347766.15036398/
2,4012732,359,1,NaN,NaN,NaN,NaN,185702,NaN,NaN,mitral valve^function^regurgitation^mild,trivial,1.2.840.113619.2.185.2475.1233148768.0.2,2807686,1.2.276.0.7230010.3.1.2.1714578744.1.1703347787.12098204,d9ffaae8-0c7c-4662-a007-e6be89f86040,370577,187228,1.2.840.113619.2.185.2475.1233148768.0.2,echo-study/1.2.276.0.7230010.3.1.2.1714578744.1.1703347787.12098204/
3,4012756,358,1,NaN,NaN,NaN,NaN,185703,NaN,NaN,local^mitral valve^function^regurgitation^trivial^358,trivial,1.2.840.113619.2.185.2475.1233150619.0.2,1120926,1.2.276.0.7230010.3.1.2.859333938.1.1703347783.12184958,df01c3d2-1684-4951-ae6d-30b82cca719b,370578,187229,1.2.840.113619.2.185.2475.1233150619.0.2,echo-study/1.2.276.0.7230010.3.1.2.859333938.1.1703347783.12184958/
4,4014422,359,1,NaN,NaN,NaN,NaN,185817,NaN,NaN,mitral valve^function^regurgitation^mild,trivial,1.2.840.113663.1500.1.242451848.1.1.20090129.145057.453,2892996,1.2.276.0.7230010.3.1.2.1714512485.1.1703426550.17045351,13f52f05-e9e5-4c0d-b18a-b84312166b06,370806,187370,1.2.840.113663.1500.1.242451848.1.1.20090129.145057.453,echo-study/1.2.276.0.7230010.3.1.2.1714512485.1.1703426550.17045351/

# Syngo

In [23]:
syn_mv_obs = observations.loc[observations['Name'] == 'MV_Regurgitation_obs']
syn_mv_obs = syn_mv_obs.dropna(subset=['Value'])

In [24]:
syn_mv_obs['Value'].unique()

array(['mild', 'trace', 'moderate', 'mild_to_moderate', 'severe',
       'moderate_to_severe', 'none'], dtype=object)

In [25]:
syn_mv_obs['Value'].value_counts()

Value
trace                 57004
mild                  22913
mild_to_moderate       5653
moderate               2931
severe                 2057
moderate_to_severe     1507
none                    536
Name: count, dtype: int64

In [26]:
mapping_two = {
    'none': 'trivial',
    'trace': 'trivial',
    'mild': 'trivial',
    'mild_to_moderate': 'moderate_or_greater',
    'moderate': 'moderate_or_greater',
    'moderate_to_severe': 'moderate_or_greater',
    'severe': 'moderate_or_greater'
}

syn_mv_obs['Regurgitation_Binary'] = syn_mv_obs['Value'].map(mapping_two)

In [27]:
len(syn_mv_obs)

92601

In [28]:
syn_mv_obs.head()

,StudyRef,ObservationID,Value,Type,Name,Regurgitation_Binary
36,1000750,151,mild,ABNORMAL,MV_Regurgitation_obs,trivial
99,1000846,151,trace,OTHER,MV_Regurgitation_obs,trivial
156,1000847,1495,trace,OTHER,MV_Regurgitation_obs,trivial
241,1000712,151,moderate,ABNORMAL,MV_Regurgitation_obs,moderate_or_greater
298,1000714,151,trace,OTHER,MV_Regurgitation_obs,trivial

In [29]:
aws_uhn.columns

Index(['STUDY_REF', 'PATIENT_ID', 'STUDY_DATE', 'STUDY_TIME',
       'ACCESSION_NUMBER', 'OriginalStudyID', 'DeidentifiedStudyID', 's3_key',
       'study_dir'],
      dtype='object')

In [31]:
# Create a boolean mask to identify matching StudyRef values
matching_mask = syn_mv_obs['StudyRef'].isin(aws_uhn['STUDY_REF'])

# Count the number of matches (True values)
number_of_matches = matching_mask.sum()

# Get the total number of unique studies in mv_obs for context
total_unique_studies = syn_mv_obs['StudyRef'].nunique()

print(f"\nTotal unique StudyRef values in mv_obs: {total_unique_studies}")
print(f"Number of 'StudyRef' values from mv_obs that are in aws_uhn: {number_of_matches}")
print(f"Percentage of matching studies: {(number_of_matches / total_unique_studies) * 100:.2f}%")

Total unique StudyRef values in mv_obs: 88712
Number of 'StudyRef' values from mv_obs that are in aws_uhn: 44312
Percentage of matching studies: 49.95%

In [37]:
import pandas as pd

# Assuming 'mv_obs' and 'aws_uhn' are your DataFrames loaded as in the screenshots.

# Step 1: Merge the two DataFrames
# We'll merge 'mv_obs' with 'aws_uhn' using 'StudyRef' and 'STUDY_REF' as the keys.
merged_df = pd.merge(syn_mv_obs, aws_uhn, left_on='StudyRef', right_on='STUDY_REF', how='inner')

# Step 2: Define the desired columns in the correct order
final_columns = [
    'STUDY_REF',
    's3_key',
    'Value',
    'Regurgitation_Binary',
    'STUDY_DATE',
    'STUDY_TIME',
    'DeidentifiedStudyID',
    'OriginalStudyID'
]

# # Step 3: Create the new table with only the specified columns
syn_mvr_labels = merged_df[final_columns]

# replacement_map = {
#     'none': 'trace',
#     'moderate_to_severe': 'severe'
# }

# # Apply the replacement to the 'Value' column
# mvr_labels['Value'] = mvr_labels['Value'].replace(replacement_map)

In [44]:
print(syn_mvr_labels.shape)
print(syn_mvr_labels['Regurgitation_Binary'].value_counts())
print(syn_mvr_labels.columns)
display(syn_mvr_labels.head())

(45152, 8)
Regurgitation_Binary
trivial                39194
moderate_or_greater     5958
Name: count, dtype: int64
Index(['STUDY_REF', 's3_key', 'Value', 'Regurgitation_Binary', 'STUDY_DATE',
       'STUDY_TIME', 'DeidentifiedStudyID', 'OriginalStudyID'],
      dtype='object')

,STUDY_REF,s3_key,Value,Regurgitation_Binary,STUDY_DATE,STUDY_TIME,DeidentifiedStudyID,OriginalStudyID
0,1000750,echo-study-2/1.2.276.0.7230010.3.1.2.895693665.1.1725195593.4282089/,mild,trivial,20150722,80635.0,1.2.276.0.7230010.3.1.2.895693665.1.1725195593.4282089,1.3.12.2.1107.5.8.9.1002655211149138.20150722120043279
1,1000846,echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1725195860.2750974/,trace,trivial,20150722,93052.0,1.2.276.0.7230010.3.1.2.842097970.1.1725195860.2750974,1.3.12.2.1107.5.8.9.1002655211149138.20150722131319960
2,1000847,echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1725195931.2751236/,trace,trivial,20150722,93351.0,1.2.276.0.7230010.3.1.2.842097970.1.1725195931.2751236,1.3.12.2.1107.5.8.9.1002655211149138.20150722132025828
3,1000712,echo-study-2/1.2.276.0.7230010.3.1.2.1714500150.1.1725195543.2219892/,moderate,moderate_or_greater,20150722,80437.0,1.2.276.0.7230010.3.1.2.1714500150.1.1725195543.2219892,1.3.12.2.1107.5.8.9.1002655211149138.20150722112601485
4,1000714,echo-study-2/1.2.276.0.7230010.3.1.2.895693665.1.1725195567.4281989/,trace,trivial,20150722,75829.0,1.2.276.0.7230010.3.1.2.895693665.1.1725195567.4281989,1.3.12.2.1107.5.8.9.1002655211149138.20150722115621748

In [91]:
print(hl_mvr_labels_final.shape)
print(hl_mvr_labels_final['Regurgitation_Binary'].value_counts())
print(hl_mvr_labels_final.columns)
hl_mvr_labels_final.head()

(170964, 19)
Regurgitation_Binary
trivial                147565
moderate_or_greater     23399
Name: count, dtype: int64
Index(['ID', 'FIN_ID', 'PHAS_ID', 'NOTE', 'SEQA_ID', 'SEQB_ID', 'SEQC_ID',
       'REP_ID', 'SEQD_ID', 'STRUCTURE_GROUP_SEQ', 'HLCODE',
       'Regurgitation_Binary', 'OriginalStudyID', 'OriginalPatientID',
       'DeidentifiedStudyID', 'DeidentifiedPatientID', 'SERI_ID', 'STUDY_ID',
       'STUDY_INSTANCE_UID'],
      dtype='object')

,ID,FIN_ID,PHAS_ID,NOTE,SEQA_ID,SEQB_ID,SEQC_ID,REP_ID,SEQD_ID,STRUCTURE_GROUP_SEQ,HLCODE,Regurgitation_Binary,OriginalStudyID,OriginalPatientID,DeidentifiedStudyID,DeidentifiedPatientID,SERI_ID,STUDY_ID,STUDY_INSTANCE_UID
0,4009034,359,1,NaN,NaN,NaN,NaN,185500,NaN,NaN,mitral valve^function^regurgitation^mild,trivial,1.2.124.113532.6.23355.16818.20090127.101618.4783525,2126381,1.2.276.0.7230010.3.1.2.1714578744.1.1703275050.10646188,ae6154bc-d23e-41d0-a5e3-141d81870b6d,370189,186986,1.2.124.113532.6.23355.16818.20090127.101618.4783525
1,4010186,358,1,NaN,NaN,NaN,NaN,185565,NaN,NaN,local^mitral valve^function^regurgitation^trivial^358,trivial,1.2.840.113619.2.185.2475.1233062503.0.21,3291779,1.2.276.0.7230010.3.1.2.1714512485.1.1703347766.15036398,31630669-811d-4ea0-ab56-30e7c1bb350d,370307,187061,1.2.840.113619.2.185.2475.1233062503.0.21
2,4012732,359,1,NaN,NaN,NaN,NaN,185702,NaN,NaN,mitral valve^function^regurgitation^mild,trivial,1.2.840.113619.2.185.2475.1233148768.0.2,2807686,1.2.276.0.7230010.3.1.2.1714578744.1.1703347787.12098204,d9ffaae8-0c7c-4662-a007-e6be89f86040,370577,187228,1.2.840.113619.2.185.2475.1233148768.0.2
3,4012756,358,1,NaN,NaN,NaN,NaN,185703,NaN,NaN,local^mitral valve^function^regurgitation^trivial^358,trivial,1.2.840.113619.2.185.2475.1233150619.0.2,1120926,1.2.276.0.7230010.3.1.2.859333938.1.1703347783.12184958,df01c3d2-1684-4951-ae6d-30b82cca719b,370578,187229,1.2.840.113619.2.185.2475.1233150619.0.2
4,4014422,359,1,NaN,NaN,NaN,NaN,185817,NaN,NaN,mitral valve^function^regurgitation^mild,trivial,1.2.840.113663.1500.1.242451848.1.1.20090129.145057.453,2892996,1.2.276.0.7230010.3.1.2.1714512485.1.1703426550.17045351,13f52f05-e9e5-4c0d-b18a-b84312166b06,370806,187370,1.2.840.113663.1500.1.242451848.1.1.20090129.145057.453

In [99]:
# Columns you want to keep
keep_cols = [
    'STUDY_REF','REP_ID','HLCODE', 'Value', 'Regurgitation_Binary','s3_key',  'STUDY_DATE',
    'STUDY_TIME', 'DeidentifiedStudyID', 'OriginalStudyID',
     
    'OriginalPatientID', 'DeidentifiedPatientID', 'SERI_ID', 'STUDY_ID',
    'STUDY_INSTANCE_UID'
]

# Combine both dataframes
uhn_mvr = pd.concat([syn_mvr_labels, hl_mvr_labels_final], ignore_index=True, sort=False)

# Drop overlapping OriginalStudyIDs (keep first occurrence)
uhn_mvr = uhn_mvr.drop_duplicates(subset='OriginalStudyID', keep='first')

# Restrict to selected columns (any missing columns will be added as NaN)
uhn_mvr = uhn_mvr.reindex(columns=keep_cols)

print(uhn_mvr.shape)
display(uhn_mvr.head())

(213340, 15)

,STUDY_REF,REP_ID,HLCODE,Value,Regurgitation_Binary,s3_key,STUDY_DATE,STUDY_TIME,DeidentifiedStudyID,OriginalStudyID,OriginalPatientID,DeidentifiedPatientID,SERI_ID,STUDY_ID,STUDY_INSTANCE_UID
0,1000750.0,NaN,NaN,mild,trivial,echo-study-2/1.2.276.0.7230010.3.1.2.895693665.1.1725195593.4282089/,20150722.0,80635.0,1.2.276.0.7230010.3.1.2.895693665.1.1725195593.4282089,1.3.12.2.1107.5.8.9.1002655211149138.20150722120043279,NaN,NaN,NaN,NaN,NaN
1,1000846.0,NaN,NaN,trace,trivial,echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1725195860.2750974/,20150722.0,93052.0,1.2.276.0.7230010.3.1.2.842097970.1.1725195860.2750974,1.3.12.2.1107.5.8.9.1002655211149138.20150722131319960,NaN,NaN,NaN,NaN,NaN
2,1000847.0,NaN,NaN,trace,trivial,echo-study-2/1.2.276.0.7230010.3.1.2.842097970.1.1725195931.2751236/,20150722.0,93351.0,1.2.276.0.7230010.3.1.2.842097970.1.1725195931.2751236,1.3.12.2.1107.5.8.9.1002655211149138.20150722132025828,NaN,NaN,NaN,NaN,NaN
3,1000712.0,NaN,NaN,moderate,moderate_or_greater,echo-study-2/1.2.276.0.7230010.3.1.2.1714500150.1.1725195543.2219892/,20150722.0,80437.0,1.2.276.0.7230010.3.1.2.1714500150.1.1725195543.2219892,1.3.12.2.1107.5.8.9.1002655211149138.20150722112601485,NaN,NaN,NaN,NaN,NaN
4,1000714.0,NaN,NaN,trace,trivial,echo-study-2/1.2.276.0.7230010.3.1.2.895693665.1.1725195567.4281989/,20150722.0,75829.0,1.2.276.0.7230010.3.1.2.895693665.1.1725195567.4281989,1.3.12.2.1107.5.8.9.1002655211149138.20150722115621748,NaN,NaN,NaN,NaN,NaN

In [100]:
uhn_mvr['Regurgitation_Binary'].value_counts()

Regurgitation_Binary
trivial                184709
moderate_or_greater     28631
Name: count, dtype: int64

In [101]:
uhn_mvr.to_csv('uhn_mvr_0911.csv')